channels:
  - conda-forge
dependencies:
  - python >= 3.12
  - pip
  - numpy
  - numba
  - galsim
  - ngmix
  - sep
  - astropy
  - metadetect
  - reproject
  - pip:
    - rocket-fft
    - lanczos @ git+https://github.com/aguinot/lanczos.git