"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np
import pytest

import ngmix

from galsim_sim import _get_obs
from metacoadd.ori_img_process import (
    get_original_cat_dtype,
    get_original_image_cat,
    get_output_original_cat,
)


ORIGINAL_FIELDS = (
    "mxx",
    "mxy",
    "myy",
    "weight",
    "flux",
    "flux_err",
    "flags",
    "psf_mxx",
    "psf_mxy",
    "psf_myy",
    "psf_flags",
)


def _make_mbobs(nband=2, noise=1.0e-4):
    """Build deterministic multiband observations."""
    mbobs = ngmix.MultiBandObsList()

    for band_index in range(nband):
        obs = _get_obs(
            np.random.RandomState(10 + band_index),
            noise=noise,
            set_noise_image=True,
            n=51,
        )
        obs.set_ormask(
            np.zeros_like(
                obs.image,
                dtype=np.int32,
            )
        )

        obslist = ngmix.ObsList()
        obslist.append(obs)
        mbobs.append(obslist)

    return mbobs


def _make_detection_catalog():
    """Build a detection catalog containing one centered object."""
    dtype = [
        ("number", np.int64),
        ("x", np.float64),
        ("y", np.float64),
        ("xx", np.float64),
        ("xy", np.float64),
        ("yy", np.float64),
    ]

    return np.array(
        [
            (
                1,
                25.0,
                25.0,
                1.0,
                0.0,
                1.0,
            )
        ],
        dtype=dtype,
    )


def test_original_catalog_dtype_and_initialization():
    """Test the output fields, dtypes, shape, and initialization."""
    n_obj = 3
    nband = 2

    dtype = np.dtype(get_original_cat_dtype(nband))
    output = get_output_original_cat(
        n_obj=n_obj,
        nband=nband,
    )

    expected_names = tuple(
        f"original_{field}_{band_index}"
        for band_index in range(nband)
        for field in ORIGINAL_FIELDS
    )

    assert dtype.names == expected_names
    assert output.dtype == dtype
    assert output.shape == (n_obj,)

    assert dtype["original_flags_0"] == np.dtype(np.int32)
    assert dtype["original_psf_flags_0"] == np.dtype(np.int32)

    for name in dtype.names:
        np.testing.assert_array_equal(
            output[name],
            np.zeros(n_obj),
        )


@pytest.mark.coverage_all_params
@pytest.mark.parametrize("psf_fitter", ["wmom", "gauss"])
def test_get_original_image_cat(psf_fitter):
    """Test original-image measurements with both PSF fitters."""
    noise = 1.0e-4
    nband = 2

    mbobs = _make_mbobs(
        nband=nband,
        noise=noise,
    )
    sep_cat = _make_detection_catalog()

    output = get_original_image_cat(
        rng=np.random.RandomState(100),
        mbobs=mbobs,
        sep_cat=sep_cat,
        cutout_size=25,
        psf_fitter=psf_fitter,
    )

    assert output.shape == (len(sep_cat),)
    assert output.dtype == np.dtype(get_original_cat_dtype(nband))

    for band_index in range(nband):
        assert output[f"original_flags_{band_index}"][0] == 0
        assert output[f"original_psf_flags_{band_index}"][0] == 0

        finite_fields = (
            "mxx",
            "mxy",
            "myy",
            "weight",
            "flux",
            "flux_err",
            "psf_mxx",
            "psf_mxy",
            "psf_myy",
        )

        for field in finite_fields:
            value = output[f"original_{field}_{band_index}"][0]
            assert np.isfinite(value)

        positive_fields = (
            "mxx",
            "myy",
            "weight",
            "flux",
            "flux_err",
            "psf_mxx",
            "psf_myy",
        )

        for field in positive_fields:
            value = output[f"original_{field}_{band_index}"][0]
            assert value > 0

        np.testing.assert_allclose(
            output[f"original_weight_{band_index}"][0],
            1.0 / noise**2,
        )

        galaxy_determinant = (
            output[f"original_mxx_{band_index}"][0]
            * output[f"original_myy_{band_index}"][0]
            - output[f"original_mxy_{band_index}"][0] ** 2
        )
        psf_determinant = (
            output[f"original_psf_mxx_{band_index}"][0]
            * output[f"original_psf_myy_{band_index}"][0]
            - output[f"original_psf_mxy_{band_index}"][0] ** 2
        )

        assert galaxy_determinant > 0
        assert psf_determinant > 0


def test_get_original_image_cat_invalid_psf_fitter():
    """Test rejection of an unsupported PSF fitter."""
    with pytest.raises(
        ValueError,
        match="PSF fitter invalid not recognized",
    ):
        get_original_image_cat(
            rng=np.random.RandomState(100),
            mbobs=_make_mbobs(),
            sep_cat=_make_detection_catalog(),
            cutout_size=25,
            psf_fitter="invalid",
        )
