"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np

from metacoadd.uberseg import fast_uberseg


def test_fast_uberseg_keeps_target_voronoi_region():
    """
    Check that weights are retained inside the target object's
    nearest-neighbor region and zeroed in the neighboring object's region.
    """
    seg = np.zeros((5, 9), dtype=np.int64)

    # Object 1 has an extended footprint.
    seg[2, 1] = 1
    seg[2, 4] = 1

    # Object 2 is three pixels away from the rightmost pixel of object 1.
    seg[2, 7] = 2

    weight = np.arange(
        1,
        seg.size + 1,
        dtype=np.float64,
    ).reshape(seg.shape)

    original_weight = weight.copy()
    original_seg = seg.copy()

    result = fast_uberseg(
        seg=seg,
        weight=weight,
        object_number=1,
    )

    # The boundary between the pixels at columns 4 and 7 lies between
    # columns 5 and 6. Columns 0--5 belong to object 1, while columns
    # 6--8 belong to object 2.
    expected = weight.astype(np.float32)
    expected[:, 6:] = 0.0

    np.testing.assert_array_equal(result, expected)

    # The rightmost segmentation pixel of object 1 must influence the
    # retained region. If only one representative position were used,
    # this pixel would incorrectly be masked.
    assert result[2, 5] == np.float32(weight[2, 5])

    # Pixels explicitly belonging to the selected object are retained.
    assert result[2, 1] == np.float32(weight[2, 1])
    assert result[2, 4] == np.float32(weight[2, 4])

    # Pixels explicitly belonging to another object are removed.
    assert result[2, 7] == 0.0

    # The wrapper converts its working weight map to float32.
    assert result.dtype == np.float32

    # A float64 input requires a converted copy, so the original inputs
    # should remain unchanged.
    np.testing.assert_array_equal(weight, original_weight)
    np.testing.assert_array_equal(seg, original_seg)


def test_fast_uberseg_single_object_keeps_all_weights():
    """
    Check that no pixels are masked when the segmentation map contains
    only the selected object.
    """
    seg = np.zeros((5, 7), dtype=np.int32)

    # Use a multi-pixel footprint so all pixels in the image are assigned
    # to some part of the selected object.
    seg[1, 2] = 4
    seg[2, 2] = 4
    seg[3, 3] = 4

    weight = np.linspace(
        0.5,
        10.0,
        seg.size,
        dtype=np.float64,
    ).reshape(seg.shape)

    result = fast_uberseg(
        seg=seg,
        weight=weight,
        object_number=4,
    )

    np.testing.assert_array_equal(
        result,
        weight.astype(np.float32),
    )
    assert np.all(result > 0)


def test_fast_uberseg_missing_object_zeros_all_weights():
    """
    Check that all weights are removed when the requested object does
    not occur in the segmentation map.
    """
    seg = np.zeros((5, 7), dtype=np.int32)
    seg[1, 1] = 2
    seg[3, 5] = 3

    weight = np.arange(
        1,
        seg.size + 1,
        dtype=np.float32,
    ).reshape(seg.shape)

    result = fast_uberseg(
        seg=seg,
        weight=weight,
        object_number=1,
    )

    np.testing.assert_array_equal(
        result,
        np.zeros_like(weight),
    )


def test_fast_uberseg_modifies_float32_weight_in_place():
    """
    Check the in-place behavior used when the supplied weight map already
    has the float32 dtype required by the MEDS implementation.
    """
    seg = np.zeros((3, 6), dtype=np.int32)
    seg[1, 1] = 1
    seg[1, 4] = 2

    weight = np.arange(
        1,
        seg.size + 1,
        dtype=np.float32,
    ).reshape(seg.shape)

    original_weight = weight.copy()

    result = fast_uberseg(
        seg=seg,
        weight=weight,
        object_number=1,
    )

    expected = original_weight.copy()
    expected[:, 3:] = 0.0

    assert result is weight
    np.testing.assert_array_equal(result, expected)
    np.testing.assert_array_equal(weight, expected)
