"""
Tests for the MBMomRunner wrapper.

The star/galaxy size-ratio and mask tests are adapted from the
metadetect fit_mbobs_wavg tests.
"""

import numpy as np

import ngmix

from metadetect import procflags

from galsim_sim import _get_obs
from metacoadd.moments.wmom_runner import MBMomRunner


WEIGHT_FWHM = 1.2


def _make_runner(
    bmask_flag=None,
    fwhm_reg=0.0,
    symmetrize=True,
):
    """Build a weighted-moment runner."""
    return MBMomRunner(
        fitter=ngmix.gaussmom.GaussMom(
            fwhm=WEIGHT_FWHM,
        ),
        fitter_name="wmom",
        bmask_flag=bmask_flag,
        fwhm_reg=fwhm_reg,
        symmetrize=symmetrize,
    )


def _make_mbobs(
    flux_factors,
    seed=10,
):
    """
    Build a multiband observation from one common simulated profile.

    The image is scaled between bands while the PSF, morphology,
    weight, and pixel scale remain unchanged.
    """
    base_obs = _get_obs(
        rng=np.random.RandomState(seed),
        noise=1.0e-6,
        n=53,
    )

    mbobs = ngmix.MultiBandObsList()

    for flux_factor in flux_factors:
        obs = base_obs.copy()

        with obs.writeable():
            obs.image[:, :] *= flux_factor

        obslist = ngmix.ObsList()
        obslist.append(obs)
        mbobs.append(obslist)

    return mbobs


def _make_star_observation(
    seed=20,
):
    """
    Make a stellar observation from the PSF generated by _get_obs.

    The object image and its PSF are identical, so their measured
    size ratio should be one.
    """
    galaxy_obs = _get_obs(
        rng=np.random.RandomState(seed),
        noise=1.0e-6,
        n=53,
    )

    object_psf = galaxy_obs.psf.copy()
    fitted_psf = galaxy_obs.psf.copy()

    return ngmix.Observation(
        image=object_psf.image.copy(),
        weight=object_psf.weight.copy(),
        bmask=np.zeros_like(
            object_psf.image,
            dtype=np.int32,
        ),
        jacobian=object_psf.jacobian,
        psf=fitted_psf,
    )


def test_mbmom_runner_input_types_and_result_mapping():
    """
    Check Observation, ObsList, and MultiBandObsList inputs.

    All representations of the same single-band observation must
    produce identical measurements.
    """
    obs = _get_obs(
        rng=np.random.RandomState(30),
        noise=1.0e-6,
        n=53,
    )

    obslist = ngmix.ObsList()
    obslist.append(obs)

    mbobs = ngmix.MultiBandObsList()
    mbobs.append(obslist)

    runner = _make_runner(
        symmetrize=False,
    )

    # Check the default inherited from MBMomRunner.
    assert runner.bmask_flag == 2**30

    results = [
        runner.go(obs),
        runner.go(obslist),
        runner.go(mbobs),
    ]

    expected_fields = {
        "flags",
        "psf_flags",
        "psf_g",
        "psf_T",
        "obj_flags",
        "s2n",
        "g",
        "g_cov",
        "T",
        "T_flags",
        "T_err",
        "T_ratio",
        "flux_flags",
        "flux",
        "flux_err",
    }

    assert set(results[0]) == expected_fields

    for result in results:
        assert result["flags"] == 0
        assert result["psf_flags"] == 0
        assert result["obj_flags"] == 0
        assert result["T_flags"] == 0
        assert result["flux_flags"] == 0

    reference = results[0]

    for result in results[1:]:
        for name in expected_fields:
            np.testing.assert_allclose(
                result[name],
                reference[name],
                rtol=0.0,
                atol=0.0,
                equal_nan=True,
            )

    # Check the wrapper's renaming of metadetect fields.
    raw_result = runner._res_[0]

    np.testing.assert_array_equal(
        results[-1]["g"],
        raw_result["wmom_g"],
    )
    np.testing.assert_array_equal(
        results[-1]["T"],
        raw_result["wmom_T"],
    )
    np.testing.assert_array_equal(
        results[-1]["flux"],
        raw_result["wmom_band_flux"],
    )

    assert runner._res is results[-1]


def test_mbmom_runner_multiband_flux_scaling():
    """
    Check that weighted flux scales linearly between bands.

    The bands have identical morphology, PSF, weight, and noise
    properties, with only the image amplitude changed.
    """
    flux_factors = np.array(
        [
            0.5,
            1.0,
            2.5,
        ]
    )

    mbobs = _make_mbobs(
        flux_factors=flux_factors,
    )

    result = _make_runner(
        symmetrize=False,
    ).go(mbobs)

    assert result["flags"] == 0
    assert result["psf_flags"] == 0
    assert result["obj_flags"] == 0

    assert result["flux"].shape == flux_factors.shape
    assert result["flux_err"].shape == flux_factors.shape
    assert result["flux_flags"].shape == flux_factors.shape

    assert np.all(result["flux"] > 0)
    assert np.all(result["flux_err"] > 0)
    assert np.all(result["flux_flags"] == 0)

    # GaussMom measures weighted rather than total flux, but the
    # result must remain exactly linear with image amplitude.
    np.testing.assert_allclose(
        result["flux"] / result["flux"][1],
        flux_factors / flux_factors[1],
        rtol=1.0e-6,
        atol=0.0,
    )

    # Morphology is shared between bands and must give a valid
    # combined moment measurement.
    assert result["T"] > 0
    assert result["psf_T"] > 0
    assert result["T_ratio"] > 1.0
    assert result["s2n"] > 0

    assert np.all(np.isfinite(result["g"]))
    assert np.all(np.isfinite(result["g_cov"]))

    np.testing.assert_allclose(
        result["T_ratio"],
        result["T"] / result["psf_T"],
        rtol=1.0e-12,
    )


def test_mbmom_runner_star_and_galaxy_size_ratio():
    """
    Check the metadetect T-ratio invariant.

    A star has the same measured size as its PSF, while the galaxy
    generated by _get_obs is extended relative to its PSF.
    """
    star_obs = _make_star_observation()

    galaxy_obs = _get_obs(
        rng=np.random.RandomState(20),
        noise=1.0e-6,
        n=53,
    )

    star_result = _make_runner(
        symmetrize=False,
    ).go(star_obs)

    galaxy_result = _make_runner(
        symmetrize=False,
    ).go(galaxy_obs)

    assert star_result["flags"] == 0
    assert galaxy_result["flags"] == 0

    np.testing.assert_allclose(
        star_result["T_ratio"],
        1.0,
        rtol=1.0e-6,
        atol=1.0e-6,
    )

    assert galaxy_result["T_ratio"] > 1.0
    assert galaxy_result["T_ratio"] > star_result["T_ratio"]


def test_mbmom_runner_regularization():
    """
    Check the Gaussian shape-regularization relation.

    Regularization leaves the measured size unchanged and suppresses
    ellipticity by adding T_reg to its denominator.
    """
    obs = _get_obs(
        rng=np.random.RandomState(40),
        noise=1.0e-4,
        n=53,
    )

    # Introduce an asymmetric missing-data region so the otherwise
    # circular simulation has a measurable nonzero ellipticity.
    center = obs.image.shape[0] // 2

    with obs.writeable():
        obs.weight[
            center:,
            center:,
        ] = 0.0

    fwhm_reg = 0.8

    unregularized = _make_runner(
        fwhm_reg=0.0,
        symmetrize=False,
    ).go(obs)

    regularized = _make_runner(
        fwhm_reg=fwhm_reg,
        symmetrize=False,
    ).go(obs)

    assert unregularized["flags"] == 0
    assert regularized["flags"] == 0

    np.testing.assert_allclose(
        regularized["T"],
        unregularized["T"],
        rtol=1.0e-12,
    )
    np.testing.assert_allclose(
        regularized["T_ratio"],
        unregularized["T_ratio"],
        rtol=1.0e-12,
    )

    assert np.linalg.norm(regularized["g"]) < np.linalg.norm(unregularized["g"])


def test_mbmom_runner_bmask_flag():
    """
    Check configured and irrelevant mask bits.

    A configured bit must set EDGE_HIT, while another mask bit must
    not prevent the measurement.
    """
    bad_bit = 2**12
    ignored_bit = 2**5

    base_obs = _get_obs(
        rng=np.random.RandomState(50),
        noise=1.0e-6,
        n=53,
    )

    bad_obs = base_obs.copy()
    ignored_obs = base_obs.copy()

    with bad_obs.writeable():
        bad_obs.bmask[2, 3] = bad_bit

    with ignored_obs.writeable():
        ignored_obs.bmask[2, 3] = ignored_bit

    bad_result = _make_runner(
        bmask_flag=bad_bit,
        symmetrize=False,
    ).go(bad_obs)

    ignored_result = _make_runner(
        bmask_flag=bad_bit,
        symmetrize=False,
    ).go(ignored_obs)

    assert (bad_result["flags"] & procflags.EDGE_HIT) != 0
    assert (bad_result["flux_flags"] & procflags.EDGE_HIT) != 0

    assert ignored_result["flags"] == 0
    assert ignored_result["flux_flags"] == 0
