"""
The ellipticity and size tests are taken from ngmix test_admom.py while the
rest of the tests were generated by ChatGPT 5.6 Sol.
"""

import copy

import galsim
import numpy as np
import pytest

import ngmix
import ngmix.flags
from ngmix.moments import fwhm_to_T

from metacoadd.moments.galsim_admom import GAdmomFitter, get_result


_FWHM_PER_SIGMA = 2.0 * np.sqrt(2.0 * np.log(2.0))


@pytest.mark.parametrize("wcs_g1", [-0.5, 0, 0.2])
@pytest.mark.parametrize("wcs_g2", [-0.2, 0, 0.5])
@pytest.mark.parametrize("g1_true", [-0.1, 0, 0.2])
@pytest.mark.parametrize("g2_true", [-0.2, 0, 0.1])
def test_galsim_admom(g1_true, g2_true, wcs_g1, wcs_g2):
    """
    Test the galsim-admom interface.
    This test mainly focus on the ellipticity and size recovery.

    Parameters
    ----------
    g1_true : float
        True g1 value for the test galaxy.
    g2_true : float
        True g2 value for the test galaxy.
    wcs_g1 : float
        g1 value for the WCS shear.
    wcs_g2 : float
        g2 value for the WCS shear.
    """
    rng = np.random.RandomState(seed=100)

    fwhm = 0.9
    image_size = 107
    cen = (image_size - 1) / 2
    gs_wcs = galsim.ShearWCS(
        0.125, galsim.Shear(g1=wcs_g1, g2=wcs_g2)
    ).jacobian()

    obj = (
        galsim.Gaussian(fwhm=fwhm)
        .shear(g1=g1_true, g2=g2_true)
        .withFlux(
            400,
        )
    )
    im = obj.drawImage(
        nx=image_size,
        ny=image_size,
        wcs=gs_wcs,
        method="no_pixel",
    ).array
    noise = np.sqrt(np.sum(im**2)) / 1e18
    wgt = np.ones_like(im) / noise**2
    scale = np.sqrt(gs_wcs.pixelArea())

    g1arr = []
    g2arr = []
    Tarr = []
    rho4arr = []
    for _ in range(50):
        shift = rng.uniform(low=-scale / 2, high=scale / 2, size=2)
        xy = gs_wcs.toImage(galsim.PositionD(shift))

        im = (
            obj.shift(dx=shift[0], dy=shift[1])
            .drawImage(
                nx=image_size,
                ny=image_size,
                wcs=gs_wcs,
                method="no_pixel",
                dtype=np.float64,
            )
            .array
        )

        jac = ngmix.Jacobian(
            y=cen + xy.y,
            x=cen + xy.x,
            dudx=gs_wcs.dudx,
            dudy=gs_wcs.dudy,
            dvdx=gs_wcs.dvdx,
            dvdy=gs_wcs.dvdy,
        )

        noisy_im = im + rng.normal(size=im.shape) * noise
        obs = ngmix.Observation(
            image=noisy_im,
            weight=wgt,
            jacobian=jac,
        )

        fitter = GAdmomFitter(guess_fwhm=fwhm)
        res = fitter.go(obs)

        if res["flags"] == 0:
            gm = res.get_gmix()
            measured_g1, measured_g2, measured_T = gm.get_g1g2T()

            g1arr.append(measured_g1)
            g2arr.append(measured_g2)
            Tarr.append(measured_T)
            rho4arr.append(res["rho4"])

            fitted_image = res.make_image()
            assert fitted_image.shape == im.shape

        res["flags"] = 5
        with pytest.raises(RuntimeError):
            res.make_image()
        with pytest.raises(RuntimeError):
            res.get_gmix()

    g1 = np.mean(g1arr)
    g2 = np.mean(g2arr)
    gtol = 1.5e-6
    assert np.abs(g1 - g1_true) < gtol, (
        g1,
        np.std(g1arr) / np.sqrt(len(g1arr)),
    )
    assert np.abs(g2 - g2_true) < gtol, (
        g2,
        np.std(g2arr) / np.sqrt(len(g2arr)),
    )

    if g1_true == 0 and g2_true == 0:
        T = np.mean(Tarr)

        assert np.abs(T - fwhm_to_T(fwhm)) < 1.0e-6
        rho4_mean = np.mean(rho4arr)
        # Gaussian profiles have rho4 = 2.
        assert np.abs(rho4_mean - 2.0) < 1.0e-5

    with pytest.raises(ValueError):
        fitter.go(None)

    # Cover invalid-covariance branches.
    tres = copy.deepcopy(res)
    tres["flags"] = 0
    tres["sums_cov"][:, :] = np.nan
    tres = get_result(tres, 1.0, 1.0)
    assert np.isnan(tres["e1err"])

    tres = copy.deepcopy(res)
    tres["flags"] = 0
    tres["pars"][4] = -1
    tres = get_result(tres, 1.0, 1.0)
    assert tres["flags"] == ngmix.flags.NONPOS_SIZE


def _make_gaussian_image(
    size=65,
    sigma_pix=4.0,
    flux=1000.0,
):
    row, col = np.mgrid[:size, :size]
    cen = (size - 1.0) / 2.0

    radius2 = (row - cen) ** 2 + (col - cen) ** 2

    image = np.exp(-0.5 * radius2 / sigma_pix**2)
    image *= flux / image.sum()

    return image


def _make_profile_image(
    profile,
    size,
    scale,
    flux,
    size_pix,
    offset=(0.0, 0.0),
):
    if profile == "gaussian":
        obj = galsim.Gaussian(
            sigma=size_pix * scale,
            flux=flux,
        )
    elif profile == "exponential":
        obj = galsim.Exponential(
            half_light_radius=size_pix * scale,
            flux=flux,
        )
    else:
        raise ValueError(f"Unknown profile: {profile}")

    obj = obj.shift(
        dx=offset[0] * scale,
        dy=offset[1] * scale,
    )

    return obj.drawImage(
        nx=size,
        ny=size,
        scale=scale,
        method="no_pixel",
        dtype=np.float64,
    ).array


def _get_guess_fwhm(
    profile,
    size_pix,
    scale,
):
    if profile == "gaussian":
        return _FWHM_PER_SIGMA * size_pix * scale

    if profile == "exponential":
        # This only needs to be a reasonable initial
        # adaptive-Gaussian size.
        return 2.0 * size_pix * scale

    raise ValueError(f"Unknown profile: {profile}")


def _make_observation(
    image,
    scale,
    noise_std,
):
    cen = (np.asarray(image.shape) - 1.0) / 2.0

    jacobian = ngmix.DiagonalJacobian(
        row=cen[0],
        col=cen[1],
        scale=scale,
    )

    weight = np.full(
        image.shape,
        1.0 / noise_std**2,
        dtype=np.float64,
    )

    return ngmix.Observation(
        image=np.asarray(
            image,
            dtype=np.float64,
        ),
        weight=weight,
        jacobian=jacobian,
    )


def _fit_observation(
    observation,
    guess_fwhm,
):
    fitter = GAdmomFitter(
        guess_fwhm=guess_fwhm,
    )

    result = fitter.go(observation)

    assert result["flags"] == 0
    assert result["flux_flags"] == 0
    assert np.all(np.isfinite(result["flux"]))
    assert np.all(np.isfinite(result["flux_err"]))
    assert np.all(result["flux_err"] > 0)

    return result


def _measure(
    image,
    scale,
    sigma_pix,
    noise_std,
):
    observation = _make_observation(
        image=image,
        scale=scale,
        noise_std=noise_std,
    )

    return _fit_observation(
        observation=observation,
        guess_fwhm=(_FWHM_PER_SIGMA * sigma_pix * scale),
    )


def _measure_fixed_window_flux(
    observation,
    pars,
    max_moment_nsig2=25.0,
):
    pixels = observation.pixels

    x0 = pars[0]
    y0 = pars[1]
    Mxx = pars[2]
    Mxy = pars[3]
    Myy = pars[4]

    detM = Mxx * Myy - Mxy**2

    if detM <= 0:
        raise ValueError("Moment matrix is not positive definite")

    w_norm = 1.0 / (2.0 * np.pi * np.sqrt(detM))

    Minv_xx = Myy / detM
    TwoMinv_xy = -2.0 * Mxy / detM
    Minv_yy = Mxx / detM

    umod = pixels["u"] - x0
    vmod = pixels["v"] - y0

    rho2 = Minv_xx * vmod**2 + TwoMinv_xy * umod * vmod + Minv_yy * umod**2

    mask = rho2 < max_moment_nsig2
    masked_rho2 = rho2[mask]

    win = np.exp(-0.5 * masked_rho2) * w_norm * pixels["area"][mask]

    wsum = np.sum(win)

    weighted_rho4 = np.sum(win * pixels["val"][mask] * masked_rho2**2)

    fnorm = observation.jacobian.area * wsum

    return weighted_rho4 / (w_norm * fnorm)


def test_flux_and_error_are_coordinate_invariant():
    """Test invariance under a change in coordinate scale."""
    flux = 1000.0
    sigma_pix = 4.0
    noise_std = 0.5

    image = _make_gaussian_image(
        sigma_pix=sigma_pix,
        flux=flux,
    )

    result_1 = _measure(
        image=image,
        scale=0.2,
        sigma_pix=sigma_pix,
        noise_std=noise_std,
    )

    result_2 = _measure(
        image=image,
        scale=0.7,
        sigma_pix=sigma_pix,
        noise_std=noise_std,
    )

    # The HSM FIT flux A*rho4 is exact
    # for a Gaussian profile.
    np.testing.assert_allclose(
        result_1["flux"][0],
        flux,
        rtol=5.0e-4,
    )

    np.testing.assert_allclose(
        result_2["flux"][0],
        flux,
        rtol=5.0e-4,
    )

    np.testing.assert_allclose(
        result_1["flux"],
        result_2["flux"],
        rtol=1.0e-8,
    )

    np.testing.assert_allclose(
        result_1["flux_err"],
        result_2["flux_err"],
        rtol=1.0e-8,
    )


def _get_fixed_window_flux_kernel(
    observation,
    pars,
    max_moment_nsig2=25.0,
):
    pixels = observation.pixels

    x0 = pars[0]
    y0 = pars[1]
    Mxx = pars[2]
    Mxy = pars[3]
    Myy = pars[4]

    detM = Mxx * Myy - Mxy**2

    if detM <= 0:
        raise ValueError("Moment matrix is not positive definite")

    w_norm = 1.0 / (2.0 * np.pi * np.sqrt(detM))

    Minv_xx = Myy / detM
    TwoMinv_xy = -2.0 * Mxy / detM
    Minv_yy = Mxx / detM

    umod = pixels["u"] - x0
    vmod = pixels["v"] - y0

    rho2 = Minv_xx * vmod**2 + TwoMinv_xy * umod * vmod + Minv_yy * umod**2

    mask = rho2 < max_moment_nsig2

    win = np.zeros(
        pixels.size,
        dtype=np.float64,
    )

    win[mask] = np.exp(-0.5 * rho2[mask]) * w_norm * pixels["area"][mask]

    wsum = np.sum(win)

    fnorm = observation.jacobian.area * wsum

    kernel = np.zeros_like(win)

    kernel[mask] = win[mask] * rho2[mask] ** 2 / (w_norm * fnorm)

    return kernel


@pytest.mark.parametrize(
    "profile,size_pix,offset",
    [
        # Well-sampled Gaussian.
        ("gaussian", 4.0, (0.0, 0.0)),
        # Moderately sampled Gaussian.
        ("gaussian", 1.5, (0.0, 0.0)),
        # Small Gaussian at different pixel phases.
        ("gaussian", 0.9, (0.0, 0.0)),
        ("gaussian", 0.9, (0.25, 0.25)),
        ("gaussian", 0.9, (0.49, 0.49)),
        # Exponential profiles.
        ("exponential", 4.0, (0.0, 0.0)),
        ("exponential", 2.0, (0.0, 0.0)),
        # A small exponential only converges reliably
        # when shifted away from the pixel center.
        ("exponential", 1.0, (0.37, 0.29)),
    ],
)
def test_fixed_window_flux_error_profiles(
    profile,
    size_pix,
    offset,
):
    """
    Compare fixed-window flux errors with analytic and MC scatter.

    Parameters
    ----------
    profile : str
        The profile type to test. Must be one of "gaussian" or "exponential".
    size_pix : float
        The size of the profile in pixels. For a Gaussian, this is sigma.
    offset : tuple of float
        The (x, y) offset of the profile center from the pixel center in
        pixels.
    """
    rng = np.random.default_rng(92841)

    flux = 1000.0
    scale = 0.2
    noise_std = 0.2
    image_size = 65

    noiseless_image = _make_profile_image(
        profile=profile,
        size=image_size,
        scale=scale,
        flux=flux,
        size_pix=size_pix,
        offset=offset,
    )

    reference_obs = _make_observation(
        image=noiseless_image,
        scale=scale,
        noise_std=noise_std,
    )

    reference_result = _fit_observation(
        observation=reference_obs,
        guess_fwhm=_get_guess_fwhm(
            profile=profile,
            size_pix=size_pix,
            scale=scale,
        ),
    )

    fixed_pars = reference_result["pars"].copy()

    kernel = _get_fixed_window_flux_kernel(
        observation=reference_obs,
        pars=fixed_pars,
    )

    fixed_reference_flux = _measure_fixed_window_flux(
        observation=reference_obs,
        pars=fixed_pars,
    )

    # The standalone fixed-window calculation
    # must reproduce the fitter calculation.
    #
    # The tolerance accounts for the different
    # floating-point summation orders used by
    # NumPy and the Numba fitter.
    np.testing.assert_allclose(
        fixed_reference_flux,
        reference_result["flux"][0],
        rtol=1.0e-7,
        atol=1.0e-10,
    )

    predicted_error = reference_result["flux_err"][0]

    # For independent, homoscedastic pixel noise,
    # the exact fixed-window variance is
    #
    # noise_std**2 * sum(kernel**2).
    analytic_error = noise_std * np.sqrt(np.sum(kernel**2))

    # This is the strongest deterministic test of
    # the reported fixed-window uncertainty.
    np.testing.assert_allclose(
        predicted_error,
        analytic_error,
        rtol=1.0e-6,
        atol=0.0,
    )

    # Monte Carlo validation of the statistical
    # interpretation of the same uncertainty.
    ntrial = 3000
    batch_size = 250

    measured_fluxes = np.empty(
        ntrial,
        dtype=np.float64,
    )

    for start in range(
        0,
        ntrial,
        batch_size,
    ):
        stop = min(
            start + batch_size,
            ntrial,
        )

        noise = rng.normal(
            loc=0.0,
            scale=noise_std,
            size=(
                stop - start,
                kernel.size,
            ),
        )

        # With a fixed window, the noisy flux is
        # exactly the noiseless flux plus the
        # pixel-noise projection onto the kernel.
        measured_fluxes[start:stop] = fixed_reference_flux + noise @ kernel

    empirical_error = np.std(
        measured_fluxes,
        ddof=1,
    )

    error_ratio = empirical_error / predicted_error

    # For 3000 realizations, the relative sampling
    # uncertainty of the standard deviation is
    # approximately 1.3%. A 5% interval is therefore
    # about a 3.9-sigma acceptance range.
    np.testing.assert_allclose(
        error_ratio,
        1.0,
        rtol=0.05,
        atol=0.0,
    )


def test_flux_s2n_scaling():
    """Test flux S/N scaling with flux and pixel noise."""
    profile = "exponential"
    size_pix = 2.0
    scale = 0.2
    image_size = 65

    configurations = {
        "reference": {
            "flux": 1000.0,
            "noise_std": 0.2,
        },
        "double_noise": {
            "flux": 1000.0,
            "noise_std": 0.4,
        },
        "double_flux": {
            "flux": 2000.0,
            "noise_std": 0.2,
        },
    }

    results = {}

    for name, config in configurations.items():
        image = _make_profile_image(
            profile=profile,
            size=image_size,
            scale=scale,
            flux=config["flux"],
            size_pix=size_pix,
        )

        observation = _make_observation(
            image=image,
            scale=scale,
            noise_std=config["noise_std"],
        )

        results[name] = _fit_observation(
            observation=observation,
            guess_fwhm=_get_guess_fwhm(
                profile=profile,
                size_pix=size_pix,
                scale=scale,
            ),
        )

    reference = results["reference"]
    double_noise = results["double_noise"]
    double_flux = results["double_flux"]

    # Changing the declared noise must not change
    # the noiseless flux measurement.
    np.testing.assert_allclose(
        double_noise["flux"],
        reference["flux"],
        rtol=1.0e-8,
    )

    # Doubling the pixel noise doubles flux_err.
    np.testing.assert_allclose(
        double_noise["flux_err"],
        2.0 * reference["flux_err"],
        rtol=1.0e-8,
    )

    # Doubling the object amplitude doubles
    # the measured FIT flux.
    np.testing.assert_allclose(
        double_flux["flux"],
        2.0 * reference["flux"],
        rtol=1.0e-8,
    )

    # In the background-dominated regime, the
    # absolute flux error is independent of flux.
    np.testing.assert_allclose(
        double_flux["flux_err"],
        reference["flux_err"],
        rtol=1.0e-8,
    )

    reference_s2n = reference["flux"] / reference["flux_err"]

    double_noise_s2n = double_noise["flux"] / double_noise["flux_err"]

    double_flux_s2n = double_flux["flux"] / double_flux["flux_err"]

    np.testing.assert_allclose(
        double_noise_s2n,
        0.5 * reference_s2n,
        rtol=1.0e-8,
    )

    np.testing.assert_allclose(
        double_flux_s2n,
        2.0 * reference_s2n,
        rtol=1.0e-8,
    )
