"""
The tests were generated by ChatGPT 5.6 Sol.
"""

from unittest.mock import Mock

import numpy as np
import pytest

import ngmix
from ngmix.gmix.gmix import _gmix_model_dict
from ngmix.moments import fwhm_to_T

from galsim_sim import _get_obs
from metacoadd import fitting
from metacoadd.fitters.fourier_fitting import FourierFitter
from metacoadd.fitting import (
    BootstrapperGuess,
    RunnerGuess,
    bootstrap_guess,
    get_fitters,
    get_gauss_psf_runner,
    get_runner,
    parse_model,
    run_fitter_guess,
)
from metacoadd.moments.wmom_runner import MBMomRunner


class _SequenceFitter:
    """Return a predefined sequence of fitter results."""

    def __init__(self, flags):
        self.flags = iter(flags)
        self.calls = []

    def go(self, obs, guess):
        """Record the call and return the next result."""
        self.calls.append((obs, np.array(guess, copy=True)))
        return {"flags": next(self.flags)}


def test_parse_model():
    """Test supported and unsupported model names."""
    models = [
        "wmom",
        "pgauss",
        "am",
        "gauss",
        "exp",
        "dev",
        "fourier_gauss",
        "fourier_exp",
        "fourier_dev",
    ]

    for model in models:
        assert parse_model(model) == model

    # Also check an ngmix model recognized by parse_model but not yet
    # implemented by the runner builders.
    unsupported = next(
        model
        for model in _gmix_model_dict
        if model not in ["gauss", "exp", "dev"]
    )
    assert parse_model(unsupported) == unsupported

    for model in ["invalid", "fourier_invalid"]:
        with pytest.raises(ValueError, match="not recognized"):
            parse_model(model)


def test_get_fitters_input():
    """Test string, list, and invalid get_fitters inputs."""
    rng = np.random.RandomState(10)

    fitters = get_fitters(
        models="wmom",
        fwhms=[1.2],
        symmetrizes=[False],
        rng=rng,
        nband=1,
        scale=0.263,
    )

    assert list(fitters) == ["wmom"]
    assert isinstance(fitters["wmom"], MBMomRunner)
    assert fitters["wmom"].symmetrize is False

    with pytest.raises(
        ValueError,
        match="models must be a string or a list",
    ):
        get_fitters(
            models=("wmom",),
            fwhms=[1.2],
            symmetrizes=[True],
            rng=rng,
            nband=1,
            scale=0.263,
        )


def test_get_fitters_types():
    """Test construction of every implemented runner type."""
    rng = np.random.RandomState(20)

    models = [
        "wmom",
        "pgauss",
        "am",
        "gauss",
        "exp",
        "dev",
        "fourier_gauss",
        "fourier_exp",
        "fourier_dev",
    ]
    fwhms = [1.2, 1.2, None, None, None, None, None, None, None]
    symmetrizes = [False, True, True, True, True, True, True, True, True]

    fitters = get_fitters(
        models=models,
        fwhms=fwhms,
        symmetrizes=symmetrizes,
        rng=rng,
        nband=2,
        scale=0.263,
        stamp_size=35,
    )

    assert list(fitters) == models

    assert isinstance(fitters["wmom"], MBMomRunner)
    assert isinstance(
        fitters["wmom"].fitter,
        ngmix.gaussmom.GaussMom,
    )
    assert fitters["wmom"].fitter_name == "wmom"
    assert fitters["wmom"].symmetrize is False

    assert isinstance(fitters["pgauss"], MBMomRunner)
    assert isinstance(
        fitters["pgauss"].fitter,
        ngmix.prepsfmom.PGaussMom,
    )
    assert fitters["pgauss"].fitter_name == "pgauss"
    assert fitters["pgauss"].symmetrize is True

    assert isinstance(fitters["am"], MBMomRunner)
    assert isinstance(fitters["am"].fitter, RunnerGuess)
    assert isinstance(
        fitters["am"].fitter.fitter,
        ngmix.admom.AdmomFitter,
    )

    for model in ["gauss", "exp", "dev"]:
        runner = fitters[model]

        assert isinstance(runner, BootstrapperGuess)
        assert isinstance(runner.runner, RunnerGuess)
        assert isinstance(
            runner.runner.fitter,
            ngmix.fitting.Fitter,
        )
        assert isinstance(
            runner.psf_runner,
            ngmix.runners.PSFRunner,
        )
        assert runner.runner.fitter.prior.nband == 2

    for model in [
        "fourier_gauss",
        "fourier_exp",
        "fourier_dev",
    ]:
        runner = fitters[model]

        assert isinstance(runner, BootstrapperGuess)
        assert isinstance(runner.runner, RunnerGuess)
        assert isinstance(runner.runner.fitter, FourierFitter)
        assert isinstance(
            runner.psf_runner,
            ngmix.runners.PSFRunner,
        )
        assert runner.runner.fitter.prior.nband == 2
        assert runner.runner.fitter._stamp_size == 35


def test_get_runner_unimplemented_models():
    """Test valid ngmix models without a runner implementation."""
    rng = np.random.RandomState(30)

    unsupported = next(
        model
        for model in _gmix_model_dict
        if model not in ["gauss", "exp", "dev"]
    )

    with pytest.raises(NotImplementedError):
        get_runner(
            unsupported,
            rng=rng,
            nband=1,
            scale=0.263,
        )

    with pytest.raises(NotImplementedError):
        get_runner(
            f"fourier_{unsupported}",
            rng=rng,
            nband=1,
            scale=0.263,
            stamp_size=35,
        )


def test_runner_guess():
    """Test generated and explicitly supplied fitter guesses."""
    obs = object()

    fitter = _SequenceFitter(flags=[1, 0])
    guesser = Mock(
        side_effect=[
            np.arange(6),
            np.arange(6) + 1,
        ]
    )
    runner = RunnerGuess(
        fitter=fitter,
        guesser=guesser,
        ntry=3,
    )

    res = runner.go(obs)

    assert res["flags"] == 0
    assert len(fitter.calls) == 2
    assert guesser.call_count == 2
    np.testing.assert_array_equal(
        fitter.calls[0][1],
        np.arange(6),
    )
    np.testing.assert_array_equal(
        fitter.calls[1][1],
        np.arange(6) + 1,
    )

    fitter = _SequenceFitter(flags=[1, 0])
    guesser = Mock()
    runner = RunnerGuess(
        fitter=fitter,
        guesser=guesser,
        ntry=3,
    )
    guess = np.arange(6, dtype="f8")

    res = runner.go(obs, guess=guess)

    assert res["flags"] == 0
    assert len(fitter.calls) == 2
    guesser.assert_not_called()

    for _, used_guess in fitter.calls:
        np.testing.assert_array_equal(used_guess, guess)


def test_run_fitter_guess_all_attempts_fail():
    """Test returning the final result after exhausting all attempts."""
    obs = object()
    guess = np.arange(6, dtype="f8")
    fitter = _SequenceFitter(flags=[2, 4, 8])

    res = run_fitter_guess(
        obs=obs,
        fitter=fitter,
        guess=guess,
        ntry=3,
    )

    assert res["flags"] == 8
    assert len(fitter.calls) == 3

    for used_obs, used_guess in fitter.calls:
        assert used_obs is obs
        np.testing.assert_array_equal(used_guess, guess)


def test_bootstrap_guess(monkeypatch):
    """Test PSF fitting, failed-PSF removal, and guess forwarding."""
    obs = object()
    filtered_obs = object()
    guess = np.arange(6, dtype="f8")
    expected = {"flags": 0}

    runner = Mock()
    runner.go.return_value = expected
    psf_runner = Mock()

    remove_failed = Mock(return_value=filtered_obs)
    monkeypatch.setattr(
        fitting,
        "remove_failed_psf_obs",
        remove_failed,
    )

    bootstrapper = BootstrapperGuess(
        runner=runner,
        psf_runner=psf_runner,
        ignore_failed_psf=True,
    )
    res = bootstrapper.go(obs, guess=guess)

    assert res is expected
    psf_runner.go.assert_called_once_with(obs=obs)
    remove_failed.assert_called_once_with(obs=obs)
    runner.go.assert_called_once_with(
        obs=filtered_obs,
        guess=guess,
    )

    runner.reset_mock()
    psf_runner.reset_mock()
    remove_failed.reset_mock()

    bootstrapper = BootstrapperGuess(
        runner=runner,
        psf_runner=psf_runner,
        ignore_failed_psf=False,
    )
    res = bootstrapper.go(obs, guess=guess)

    assert res is expected
    psf_runner.go.assert_called_once_with(obs=obs)
    remove_failed.assert_not_called()
    runner.go.assert_called_once_with(
        obs=obs,
        guess=guess,
    )

    runner.reset_mock()
    psf_runner.reset_mock()

    res = bootstrap_guess(
        obs=obs,
        runner=runner,
        guess=guess,
        psf_runner=None,
    )

    assert res is expected
    psf_runner.go.assert_not_called()
    runner.go.assert_called_once_with(
        obs=obs,
        guess=guess,
    )


def test_gauss_psf_runner_same():
    """Test reproducibility of Gaussian PSF fitting."""
    obs1 = _get_obs(
        np.random.RandomState(45),
        noise=1.0e-4,
        n=35,
    )
    obs2 = _get_obs(
        np.random.RandomState(45),
        noise=1.0e-4,
        n=35,
    )

    runner1 = get_gauss_psf_runner(
        np.random.RandomState(10),
    )
    runner2 = get_gauss_psf_runner(
        np.random.RandomState(10),
    )

    res1 = runner1.go(obs1)
    res2 = runner2.go(obs2)

    assert res1["flags"] == 0
    assert res2["flags"] == 0

    np.testing.assert_allclose(
        res1["pars"],
        res2["pars"],
    )
    np.testing.assert_allclose(
        res1["pars_cov"],
        res2["pars_cov"],
    )


def test_moment_runners_smoke():
    """Test weighted-moment and pre-PSF-moment runners."""
    for model in ["wmom", "pgauss"]:
        obs = _get_obs(
            np.random.RandomState(50),
            noise=1.0e-4,
            n=35,
        )
        runner = get_runner(
            model=model,
            fwhm=1.2,
            symmetrize=True,
            rng=np.random.RandomState(51),
            nband=1,
            scale=0.263,
        )

        res = runner.go(obs)

        assert res["flags"] == 0
        assert np.all(np.isfinite(res["T"]))
        assert np.all(np.isfinite(res["flux"]))


def test_gauss_runner_smoke():
    """Test a Gaussian model fit with generated and explicit guesses."""
    obs = _get_obs(
        np.random.RandomState(60),
        noise=1.0e-4,
        n=35,
    )
    runner = get_runner(
        model="gauss",
        rng=np.random.RandomState(61),
        nband=1,
        scale=0.263,
    )

    res = runner.go(obs)

    assert res["flags"] == 0
    assert np.all(np.isfinite(res["pars"]))
    assert np.all(np.isfinite(res["flux"]))

    obs = _get_obs(
        np.random.RandomState(60),
        noise=1.0e-4,
        n=35,
    )
    runner = get_runner(
        model="gauss",
        rng=np.random.RandomState(61),
        nband=1,
        scale=0.263,
    )
    guess = np.array(
        [
            0.0,
            0.0,
            0.0,
            0.0,
            fwhm_to_T(0.7),
            1.0,
        ]
    )

    res = runner.go(obs, guess=guess)

    assert res["flags"] == 0
    assert np.all(np.isfinite(res["pars"]))
    assert np.all(np.isfinite(res["flux"]))
