"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np
import pytest

import ngmix

from galsim_sim import _get_obs
from metacoadd.metadetect import MetaDetect


MCAL_TYPES = [
    "noshear",
    "1p",
    "1m",
    "2p",
    "2m",
]

MCAL_CONFIG = {
    "step": 0.01,
    "types": MCAL_TYPES,
    "psf": "fitgauss",
    "use_noise_image": True,
    "fixnoise": True,
    "has_pixel": False,
}


def _make_mbobs(nband=2, seed=10):
    """Build deterministic multiband observations."""
    mbobs = ngmix.MultiBandObsList()

    for band_index in range(nband):
        obs = _get_obs(
            np.random.RandomState(seed + band_index),
            noise=1.0e-4,
            set_noise_image=True,
            n=35,
        )
        obs.set_ormask(
            np.zeros_like(
                obs.image,
                dtype=np.int32,
            )
        )

        obslist = ngmix.ObsList()
        obslist.append(obs)
        mbobs.append(obslist)

    return mbobs


def _make_md(**kwargs):
    """Build a MetaDetect instance with a complete configuration."""
    config = {
        "rng": np.random.RandomState(20),
        "models": ["wmom"],
        "fwhms": [1.2],
        "symmetrizes": [True],
        "stamp_size": 35,
        "coadd_fscale": [[1.0], [1.0]],
        "mcal_config": MCAL_CONFIG.copy(),
    }
    config.update(kwargs)
    return MetaDetect(**config)


def _add_imcom_layers(mbobs):
    """Attach deterministic coverage maps to the observations."""
    for band_index, obslist in enumerate(mbobs):
        for obs in obslist:
            obs.coverage = np.full(
                obs.image.shape,
                band_index + 1.0,
                dtype=np.float64,
            )


def _assert_successful_measurements(catalog, model, nband):
    """Check that a real fitter produced useful measurements."""
    flags_name = f"{model}_flags"

    assert flags_name in catalog.dtype.names
    assert f"{model}_T" in catalog.dtype.names
    assert f"{model}_g1" in catalog.dtype.names
    assert f"{model}_g2" in catalog.dtype.names

    successful = catalog[flags_name] == 0
    assert np.any(successful)

    fields = [
        f"{model}_T",
        f"{model}_Tpsf",
        f"{model}_s2n",
        f"{model}_g1",
        f"{model}_g2",
    ]

    for band_index in range(nband):
        fields.extend(
            [
                f"{model}_flux_{band_index}",
                f"{model}_flux_err_{band_index}",
            ]
        )

    for field in fields:
        assert field in catalog.dtype.names
        assert np.all(np.isfinite(catalog[field][successful]))


def test_init_defaults_and_stamp_size():
    """Test default metacal settings and odd stamp-size enforcement."""
    md = MetaDetect(
        rng=np.random.RandomState(30),
        models=["wmom"],
        fwhms=[1.2],
        symmetrizes=[True],
        stamp_size=34,
        coadd_fscale=[[1.0]],
    )

    assert md._stamp_size == 35
    assert md.mcal_config["step"] == 0.01
    assert md.mcal_config["types"] == MCAL_TYPES
    assert md.mcal_config["fixnoise"] is True
    assert md.mcal_config["use_noise_image"] is True
    assert md.mcal_config["has_pixel"] is False

    with pytest.raises(
        ValueError,
        match="mcal_config must be a dictionary",
    ):
        MetaDetect(
            rng=np.random.RandomState(31),
            mcal_config="invalid",
        )


def test_init_optional_catalog_validation():
    """Test original-image and IMCOM configuration validation."""
    base = {
        "rng": np.random.RandomState(40),
        "mcal_config": MCAL_CONFIG.copy(),
    }

    with pytest.raises(
        ValueError,
        match="original_image_config must contain",
    ):
        MetaDetect(
            **base,
            original_image_config={},
        )

    with pytest.raises(
        ValueError,
        match="original_image_config 'mcal_type_ref'",
    ):
        MetaDetect(
            **base,
            original_image_config={
                "mcal_type_ref": "invalid",
            },
        )

    with pytest.raises(
        ValueError,
        match="imcom_map_config must contain",
    ):
        MetaDetect(
            **base,
            imcom_map_config={
                "layers": {},
            },
        )

    with pytest.raises(
        ValueError,
        match="imcom_map_config 'mcal_type_ref'",
    ):
        MetaDetect(
            **base,
            imcom_map_config={
                "mcal_type_ref": "invalid",
                "layers": {},
            },
        )

    md = MetaDetect(
        **base,
        original_image_config={
            "mcal_type_ref": "noshear",
        },
        imcom_map_config={
            "mcal_type_ref": "noshear",
            "layers": {
                "Coverage": {},
            },
        },
    )

    assert md._do_original_image is True
    assert md._original_image_mcal_type_ref == "noshear"
    assert md._do_imcom_map is True
    assert md._imcom_map_mcal_type_ref == "noshear"


def test_go_input_and_coadd_validation():
    """Test input type and coadd configuration validation."""
    md = _make_md()

    with pytest.raises(
        ValueError,
        match="mb_obs must be an instance",
    ):
        md.go(object())

    invalid_configs = [
        {
            "coadd_fscale": None,
            "coadd_zeropoints": None,
            "match": ("Either coadd_zeropoints or coadd_fscale"),
        },
        {
            "coadd_fscale": [
                [1.0],
                [1.0],
            ],
            "coadd_zeropoints": [
                [30.0],
                [30.0],
            ],
            "match": ("Either coadd_zeropoints or coadd_fscale"),
        },
        {
            "coadd_fscale": [[1.0]],
            "coadd_zeropoints": None,
            "match": ("coadd_fscale must have the same length"),
        },
        {
            "coadd_fscale": None,
            "coadd_zeropoints": [[30.0]],
            "match": ("coadd_zeropoints must have the same length"),
        },
    ]

    mcal_config = MCAL_CONFIG.copy()
    mcal_config["types"] = ["noshear"]

    for config in invalid_configs:
        mbobs = _make_mbobs()

        md = _make_md(
            coadd_fscale=config["coadd_fscale"],
            coadd_zeropoints=(config["coadd_zeropoints"]),
            mcal_config=mcal_config,
        )

        with pytest.raises(
            ValueError,
            match=config["match"],
        ):
            md.go(mbobs)


def test_go_without_multiband_coadd():
    """Run real detection using only the first observation."""
    mcal_config = MCAL_CONFIG.copy()
    mcal_config["types"] = ["noshear"]

    mbobs = _make_mbobs()
    shape = mbobs[0][0].image.shape

    mbobs[0][0].set_bmask(
        np.full(
            shape,
            1,
            dtype=np.int32,
        )
    )
    mbobs[1][0].set_bmask(
        np.full(
            shape,
            2,
            dtype=np.int32,
        )
    )
    mbobs[0][0].set_ormask(
        np.full(
            shape,
            4,
            dtype=np.int32,
        )
    )
    mbobs[1][0].set_ormask(
        np.full(
            shape,
            8,
            dtype=np.int32,
        )
    )

    md = _make_md(
        coadd_multiband=False,
        mcal_config=mcal_config,
        detect_thresh=5.0,
        detect_kernel=[[1.0]],
    )

    result = md.go(mbobs)

    assert set(result) == {"noshear"}

    catalog = result["noshear"]
    assert catalog.size > 0

    # Only the first observation supplies the detection masks.
    assert np.all((catalog["bmask"] & 1) == 1)
    assert np.all((catalog["bmask"] & 2) == 0)
    assert np.all((catalog["ormask"] & 4) == 4)
    assert np.all((catalog["ormask"] & 8) == 0)

    _assert_successful_measurements(
        catalog,
        model="wmom",
        nband=2,
    )


def test_go_original_and_imcom_catalogs():
    """Run the real reference and placeholder branches."""
    mcal_config = MCAL_CONFIG.copy()
    mcal_config["types"] = [
        "noshear",
        "1p",
    ]

    original_config = {
        "mcal_type_ref": "noshear",
        "wmom_fwhm": 0.5,
        "psf_fitter": "wmom",
    }
    imcom_config = {
        "mcal_type_ref": "noshear",
        "layers": {
            "Coverage": {
                "combine": "mean",
                "stat": "std",
            },
        },
    }

    mbobs = _make_mbobs()
    _add_imcom_layers(mbobs)

    md = _make_md(
        mcal_config=mcal_config,
        original_image_config=original_config,
        imcom_map_config=imcom_config,
        do_uberseg=True,
        detect_thresh=5.0,
        detect_kernel=[[1.0]],
    )

    result = md.go(mbobs)

    assert set(result) == {
        "noshear",
        "1p",
    }
    assert result["noshear"].size > 0
    assert result["1p"].size > 0

    for band_index in range(2):
        flags_name = f"original_flags_{band_index}"
        flux_name = f"original_flux_{band_index}"

        assert np.any(result["noshear"][flags_name] != 42)
        assert np.all(result["1p"][flags_name] == 42)

        good = result["noshear"][flags_name] == 0
        if np.any(good):
            assert np.all(np.isfinite(result["noshear"][flux_name][good]))

        mean_name = f"IMCOM_Coverage_mean_{band_index}"
        std_name = f"IMCOM_Coverage_std_{band_index}"

        np.testing.assert_allclose(
            result["noshear"][mean_name],
            band_index + 1.0,
        )
        np.testing.assert_allclose(
            result["noshear"][std_name],
            0.0,
        )

        # Non-reference branches contain the real
        # get_output_imcom_map_cat sentinel.
        np.testing.assert_allclose(
            result["1p"][mean_name],
            -10.0,
        )
        np.testing.assert_allclose(
            result["1p"][std_name],
            -10.0,
        )
