"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np
import pytest

import ngmix

from metacoadd.coadd import (
    Coadd,
    CoaddAverage,
    CoaddMedian,
    CoaddWeightedAverage,
    get_coadd_class,
)


SHAPE = (2, 3)
FSCALE = [[1.0, 2.0], [0.5, 4.0]]


def _make_observation(image, noise, weight):
    """Build an ngmix observation for the coadd tests."""
    return ngmix.Observation(
        image=np.full(SHAPE, image, dtype=np.float64),
        noise=np.full(SHAPE, noise, dtype=np.float64),
        weight=np.asarray(weight, dtype=np.float64),
    )


def _make_mb_obs(image_values, noise_values, weights):
    """Build an ngmix MultiBandObsList from NumPy arrays."""
    image_values = np.asarray(image_values, dtype=np.float64)
    noise_values = np.asarray(noise_values, dtype=np.float64)
    weights = np.asarray(weights, dtype=np.float64)

    assert image_values.shape == noise_values.shape
    assert weights.shape[:2] == image_values.shape
    assert weights.shape[2:] == SHAPE

    mb_obs = ngmix.MultiBandObsList()

    for band_index in range(image_values.shape[0]):
        obs_list = ngmix.ObsList()

        for obs_index in range(image_values.shape[1]):
            obs_list.append(
                _make_observation(
                    image=image_values[band_index, obs_index],
                    noise=noise_values[band_index, obs_index],
                    weight=weights[band_index, obs_index],
                )
            )

        mb_obs.append(obs_list)

    return mb_obs


def _constant_weight_maps(weight_values):
    """Create constant weight maps with shape (band, observation, y, x)."""
    weight_values = np.asarray(weight_values, dtype=np.float64)

    return np.broadcast_to(
        weight_values[..., None, None],
        (*weight_values.shape, *SHAPE),
    ).copy()


@pytest.fixture
def mb_obs():
    """Build two bands containing two observations each."""
    image_values = np.asarray(
        [
            [1.0, 3.0],
            [5.0, 7.0],
        ]
    )

    # One map per observation, reshaped as
    # (number of bands, observations per band, y, x).
    weights = np.asarray(
        [
            [[1, 4, 0], [0, 1, 0]],
            [[9, 0, 0], [4, 1, 0]],
            [[0, 16, 0], [9, 1, 0]],
            [[0, 0, 0], [16, 1, 0]],
        ],
        dtype=np.float64,
    ).reshape(2, 2, *SHAPE)

    return _make_mb_obs(
        image_values=image_values,
        noise_values=10 * image_values,
        weights=weights,
    )


def test_mb_obs_fixture(mb_obs):
    """Check that the fixture contains real ngmix observation objects."""
    assert isinstance(mb_obs, ngmix.MultiBandObsList)
    assert len(mb_obs) == 2

    for obs_list in mb_obs:
        assert isinstance(obs_list, ngmix.ObsList)
        assert len(obs_list) == 2

        for obs in obs_list:
            assert isinstance(obs, ngmix.Observation)
            assert obs.image.shape == SHAPE
            assert obs.noise.shape == SHAPE
            assert obs.weight.shape == SHAPE


def test_default_fscale_and_base_make(mb_obs):
    """Test default scaling, missing masks, and base make."""
    coadd = Coadd(mb_obs)

    np.testing.assert_array_equal(
        coadd.fscale,
        np.ones((2, 2)),
    )

    bmask, ormask = coadd.make_masks()

    assert bmask is None
    assert ormask is None

    with pytest.raises(
        NotImplementedError,
        match="implemented in subclasses",
    ):
        coadd.make()


def test_explicit_fscale(mb_obs):
    """Test explicit per-band and per-observation flux scales."""
    coadd = Coadd(
        mb_obs,
        fscale=FSCALE,
    )

    assert coadd.fscale.dtype == np.float64
    np.testing.assert_array_equal(
        coadd.fscale,
        FSCALE,
    )


def test_zeropoints_are_converted_to_fscale(mb_obs):
    """Test zeropoint-to-flux-scale conversion."""
    zeropoints = [
        [30.0, 31.0],
        [29.0, 30.0],
    ]
    target_zp = 29.5

    coadd = Coadd(
        mb_obs,
        zeropoints=zeropoints,
        target_zp=target_zp,
    )

    expected = 10 ** (-0.4 * (np.asarray(zeropoints) - target_zp))

    np.testing.assert_allclose(
        coadd.fscale,
        expected,
    )


def test_invalid_flux_scaling_inputs(mb_obs):
    """Test every invalid combination of flux scaling inputs."""
    with pytest.raises(
        ValueError,
        match="fscale must have the same length as the number of bands",
    ):
        Coadd(
            mb_obs,
            fscale=[[1.0, 1.0]],
        )

    # This reaches lines 38-39 and the exception starting on line 42.
    with pytest.raises(
        ValueError,
        match=(
            "fscale must have the same length as the number of observations"
        ),
    ):
        Coadd(
            mb_obs,
            fscale=[
                [1.0, 1.0],
                [1.0],
            ],
        )

    # This reaches the exception starting on line 48.
    with pytest.raises(
        ValueError,
        match=("zeropoints must have the same length as the number of bands"),
    ):
        Coadd(
            mb_obs,
            zeropoints=[[30.0, 30.0]],
        )

    # This reaches lines 57-58 and the exception starting on line 63.
    with pytest.raises(
        ValueError,
        match=(
            "zeropoints must have the same length as the "
            "number of observations"
        ),
    ):
        Coadd(
            mb_obs,
            zeropoints=[
                [30.0, 30.0],
                [30.0],
            ],
        )

    # This reaches the exception starting on line 70.
    with pytest.raises(
        ValueError,
        match=("Either fscale or zeropoints must be provided, but not both"),
    ):
        Coadd(
            mb_obs,
            fscale=FSCALE,
            zeropoints=[
                [30.0, 30.0],
                [30.0, 30.0],
            ],
        )


def test_make_masks(mb_obs):
    """Test bitwise mask combination across observations."""
    bmask_bits = np.asarray(
        [
            [2**0, 2**1],
            [2**2, 2**3],
        ],
        dtype=np.int64,
    )
    ormask_bits = np.asarray(
        [
            [2**4, 2**5],
            [2**6, 2**7],
        ],
        dtype=np.int64,
    )

    for band_index, obslist in enumerate(mb_obs):
        for obs_index, obs in enumerate(obslist):
            obs.set_bmask(
                np.full(
                    SHAPE,
                    bmask_bits[
                        band_index,
                        obs_index,
                    ],
                    dtype=np.int64,
                )
            )
            obs.set_ormask(
                np.full(
                    SHAPE,
                    ormask_bits[
                        band_index,
                        obs_index,
                    ],
                    dtype=np.int64,
                )
            )

    bmask, ormask = Coadd(mb_obs).make_masks()

    expected_bmask = np.full(
        SHAPE,
        2**0 | 2**1 | 2**2 | 2**3,
        dtype=np.int64,
    )
    expected_ormask = np.full(
        SHAPE,
        2**4 | 2**5 | 2**6 | 2**7,
        dtype=np.int64,
    )

    np.testing.assert_array_equal(
        bmask,
        expected_bmask,
    )
    np.testing.assert_array_equal(
        ormask,
        expected_ormask,
    )

    assert bmask.dtype == np.int64
    assert ormask.dtype == np.int64

    # Mask values are preserved even where every input
    # observation has zero weight.
    assert np.all(
        [obs.weight[0, 2] == 0 for obslist in mb_obs for obs in obslist]
    )
    assert bmask[0, 2] == 15
    assert ormask[0, 2] == 240


def test_make_masks_with_bmask_only(mb_obs):
    """Test that bmask and ormask are independent."""
    expected = np.zeros(
        SHAPE,
        dtype=np.int64,
    )

    for index, obs in enumerate(obs for obslist in mb_obs for obs in obslist):
        mask = np.zeros(
            SHAPE,
            dtype=np.int64,
        )
        mask[index // SHAPE[1], index % SHAPE[1]] = 2**index
        obs.set_bmask(mask)

        expected |= mask

    bmask, ormask = Coadd(mb_obs).make_masks()

    np.testing.assert_array_equal(
        bmask,
        expected,
    )
    assert ormask is None


def test_make_masks_requires_all_bmasks(mb_obs):
    """Reject bmask present on only some observations."""
    mb_obs[0][0].set_bmask(
        np.ones(
            SHAPE,
            dtype=np.int64,
        )
    )

    with pytest.raises(
        ValueError,
        match=("bmask must be set on all observations or none"),
    ):
        Coadd(mb_obs).make_masks()


def test_make_masks_requires_all_ormasks(mb_obs):
    """Reject ormask present on only some observations."""
    mb_obs[1][0].set_ormask(
        np.ones(
            SHAPE,
            dtype=np.int64,
        )
    )

    with pytest.raises(
        ValueError,
        match=("ormask must be set on all observations or none"),
    ):
        Coadd(mb_obs).make_masks()


def test_average_coadd(mb_obs):
    """Test average image, noise, weight"""
    image, noise, weight = CoaddAverage(
        mb_obs,
        fscale=FSCALE,
    ).make()

    expected_image = np.asarray(
        [
            [3.5, 1.75, 0.0],
            [73 / 6, 9.375, 0.0],
        ]
    )
    expected_noise = np.asarray(
        [
            [35.0, 17.5, 0.0],
            [365 / 3, 93.75, 0.0],
        ]
    )
    expected_weight = np.asarray(
        [
            [36 / 13, 256 / 17, 0.0],
            [324 / 73, 64 / 85, 0.0],
        ]
    )

    np.testing.assert_allclose(image, expected_image)
    np.testing.assert_allclose(noise, expected_noise)
    np.testing.assert_allclose(weight, expected_weight)


def test_weighted_average_coadd(mb_obs):
    """Test weighted image, noise, weight"""
    image, noise, weight = CoaddWeightedAverage(
        mb_obs,
    ).make()

    expected_image = np.asarray(
        [
            [2.8, 4.2, 0.0],
            [169 / 29, 4.0, 0.0],
        ]
    )
    expected_weight = np.asarray(
        [
            [10.0, 20.0, 0.0],
            [29.0, 4.0, 0.0],
        ]
    )

    np.testing.assert_allclose(image, expected_image)
    np.testing.assert_allclose(noise, 10 * expected_image)
    np.testing.assert_allclose(weight, expected_weight)


def test_median_coadd_with_odd_number_of_images():
    """Test median coaddition with an odd number of images."""
    mb_obs = _make_mb_obs(
        image_values=[[1.0, 3.0, 5.0]],
        noise_values=[[10.0, 30.0, 50.0]],
        weights=_constant_weight_maps([[1.0, 4.0, 9.0]]),
    )

    image, noise, weight = CoaddMedian(mb_obs).make()

    expected_weight = 2.0 / np.pi * ((1 + 2 + 3) / 3) ** 2 * (3 + np.pi - 2)

    np.testing.assert_allclose(
        image,
        np.full(SHAPE, 3.0),
    )
    np.testing.assert_allclose(
        noise,
        np.full(SHAPE, 30.0),
    )
    np.testing.assert_allclose(
        weight,
        np.full(SHAPE, expected_weight),
    )


def test_median_coadd_with_even_number_of_images():
    """Test median coaddition with an even number of images."""
    mb_obs = _make_mb_obs(
        image_values=[
            [1.0, 3.0],
            [5.0, 7.0],
        ],
        noise_values=[
            [10.0, 30.0],
            [50.0, 70.0],
        ],
        weights=_constant_weight_maps(
            [
                [1.0, 4.0],
                [9.0, 16.0],
            ]
        ),
    )

    image, noise, weight = CoaddMedian(mb_obs).make()

    expected_weight = (
        2.0 / np.pi * ((1 + 2 + 3 + 4) / 4) ** 2 * (4 + np.pi / 2 - 1)
    )

    np.testing.assert_allclose(
        image,
        np.full(SHAPE, 4.0),
    )
    np.testing.assert_allclose(
        noise,
        np.full(SHAPE, 40.0),
    )
    np.testing.assert_allclose(
        weight,
        np.full(SHAPE, expected_weight),
    )


def test_get_coadd_class():
    """Test every supported coadd type and the weighted alias."""
    assert get_coadd_class("average") is CoaddAverage

    # These assertions reach lines 212 and 214.
    assert get_coadd_class("weighted_average") is CoaddWeightedAverage
    assert get_coadd_class("weighted") is CoaddWeightedAverage
    assert get_coadd_class("median") is CoaddMedian

    with pytest.raises(
        ValueError,
        match="Unknown coadd type: sum",
    ):
        get_coadd_class("sum")
