"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np
import pytest

import ngmix

from metacoadd.imcom_maps import (
    extract_imcom_maps,
    get_combine_func,
    get_imcom_map_cat_dtype,
    get_output_imcom_map_cat,
    get_stat_func,
)


SHAPE = (3, 3)

SEG_MAP = np.asarray(
    [
        [0, 1, 1],
        [1, 2, 2],
        [2, 0, 0],
    ],
    dtype=np.int32,
)

IMCOM_MAP_CONFIG = {
    "MeanMap": {},
    "MedianMap": {
        "combine": "median",
        "stat": "mad",
    },
    "SumMap": {
        "combine": "sum",
        "stat": "var",
    },
    "MinMap": {
        "combine": "min",
        "stat": "std",
    },
    "MaxMap": {
        "combine": "max",
        "stat": "std",
    },
}


def _make_mbobs(layer_names=None):
    """Build two bands containing deterministic IMCOM map layers."""
    if layer_names is None:
        layer_names = IMCOM_MAP_CONFIG

    mbobs = ngmix.MultiBandObsList()

    for band_index in range(2):
        values = (
            np.arange(np.prod(SHAPE), dtype=np.float64).reshape(SHAPE)
            + 10 * band_index
        )
        obs = ngmix.Observation(
            image=np.zeros(SHAPE, dtype=np.float64),
            weight=np.ones(SHAPE, dtype=np.float64),
        )

        for layer_name in layer_names:
            setattr(
                obs,
                layer_name.lower(),
                values.copy(),
            )

        obslist = ngmix.ObsList()
        obslist.append(obs)
        mbobs.append(obslist)

    return mbobs


def _make_sep_cat(n_obj=2):
    """Build a minimal detection catalog."""
    sep_cat = np.zeros(
        n_obj,
        dtype=[
            ("number", np.int32),
            ("x", np.float64),
            ("y", np.float64),
        ],
    )
    sep_cat["number"] = np.arange(1, n_obj + 1)
    return sep_cat


def test_get_combine_func():
    """Test every supported map-combination function."""
    values = np.asarray([1.0, 2.0, 8.0, 9.0])
    expected = {
        "mean": 5.0,
        "median": 5.0,
        "sum": 20.0,
        "min": 1.0,
        "max": 9.0,
    }

    for name, expected_value in expected.items():
        combine_func = get_combine_func(name)
        assert combine_func(values) == expected_value

    with pytest.raises(
        ValueError,
        match="Combine function invalid not recognized",
    ):
        get_combine_func("invalid")


def test_get_stat_func():
    """Test every supported statistical function."""
    values = np.asarray([1.0, 2.0, 8.0, 9.0])

    assert get_stat_func("std") is np.std
    assert get_stat_func("var") is np.var

    np.testing.assert_allclose(
        get_stat_func("std")(values),
        np.std(values),
    )
    np.testing.assert_allclose(
        get_stat_func("var")(values),
        np.var(values),
    )
    np.testing.assert_allclose(
        get_stat_func("mad")(values),
        3.5,
    )

    with pytest.raises(
        ValueError,
        match="Stat function invalid not recognized",
    ):
        get_stat_func("invalid")


def test_get_imcom_map_cat_dtype():
    """Test output field names, order, defaults, and dtypes."""
    config = {
        "MeanMap": {},
        "MaxMap": {
            "combine": "max",
            "stat": "mad",
        },
    }

    dtype = np.dtype(
        get_imcom_map_cat_dtype(
            imcom_map_config=config,
            nband=2,
        )
    )

    expected_names = (
        "IMCOM_MeanMap_mean_0",
        "IMCOM_MeanMap_std_0",
        "IMCOM_MaxMap_max_0",
        "IMCOM_MaxMap_mad_0",
        "IMCOM_MeanMap_mean_1",
        "IMCOM_MeanMap_std_1",
        "IMCOM_MaxMap_max_1",
        "IMCOM_MaxMap_mad_1",
    )

    assert dtype.names == expected_names

    for name in dtype.names:
        assert dtype[name] == np.dtype(np.float64)


def test_get_output_imcom_map_cat():
    """Test output allocation and initial sentinel values."""
    config = {
        "MeanMap": {},
        "MaxMap": {
            "combine": "max",
            "stat": "mad",
        },
    }

    output = get_output_imcom_map_cat(
        n_obj=3,
        imcom_map_config=config,
        nband=2,
    )

    assert output.shape == (3,)

    expected_names = np.dtype(
        get_imcom_map_cat_dtype(
            imcom_map_config=config,
            nband=2,
        )
    ).names
    assert output.dtype.names == expected_names

    for name in output.dtype.names:
        np.testing.assert_array_equal(
            output[name],
            np.full(3, -10.0),
        )


def test_extract_imcom_maps():
    """Test extraction of all supported statistics in two bands."""
    mbobs = _make_mbobs()
    sep_cat = _make_sep_cat()

    output = extract_imcom_maps(
        mbobs=mbobs,
        sep_cat=sep_cat,
        seg_map=SEG_MAP,
        config={"layers": IMCOM_MAP_CONFIG},
    )

    assert output.shape == (2,)

    expected_std = np.sqrt(2.0 / 3.0)
    expected_var = 2.0 / 3.0

    for band_index in range(2):
        shift = 10.0 * band_index

        np.testing.assert_allclose(
            output[f"IMCOM_MeanMap_mean_{band_index}"],
            np.asarray([2.0, 5.0]) + shift,
        )
        np.testing.assert_allclose(
            output[f"IMCOM_MeanMap_std_{band_index}"],
            [expected_std, expected_std],
        )

        np.testing.assert_allclose(
            output[f"IMCOM_MedianMap_median_{band_index}"],
            np.asarray([2.0, 5.0]) + shift,
        )
        np.testing.assert_allclose(
            output[f"IMCOM_MedianMap_mad_{band_index}"],
            [1.0, 1.0],
        )

        np.testing.assert_allclose(
            output[f"IMCOM_SumMap_sum_{band_index}"],
            np.asarray([6.0, 15.0]) + 3.0 * shift,
        )
        np.testing.assert_allclose(
            output[f"IMCOM_SumMap_var_{band_index}"],
            [expected_var, expected_var],
        )

        np.testing.assert_allclose(
            output[f"IMCOM_MinMap_min_{band_index}"],
            np.asarray([1.0, 4.0]) + shift,
        )
        np.testing.assert_allclose(
            output[f"IMCOM_MinMap_std_{band_index}"],
            [expected_std, expected_std],
        )

        np.testing.assert_allclose(
            output[f"IMCOM_MaxMap_max_{band_index}"],
            np.asarray([3.0, 6.0]) + shift,
        )
        np.testing.assert_allclose(
            output[f"IMCOM_MaxMap_std_{band_index}"],
            [expected_std, expected_std],
        )


def test_extract_imcom_maps_missing_layer():
    """Test the error raised when a layer was not propagated."""
    mbobs = _make_mbobs(layer_names=["MeanMap"])
    sep_cat = _make_sep_cat()

    with pytest.raises(
        ValueError,
        match="IMCOM layer MissingMap was not propagated",
    ):
        extract_imcom_maps(
            mbobs=mbobs,
            sep_cat=sep_cat,
            seg_map=SEG_MAP,
            config={
                "layers": {
                    "MissingMap": {},
                }
            },
        )


def test_extract_imcom_maps_empty_catalog():
    """Test extraction when no objects were detected."""
    mbobs = _make_mbobs()
    sep_cat = _make_sep_cat(n_obj=0)

    output = extract_imcom_maps(
        mbobs=mbobs,
        sep_cat=sep_cat,
        seg_map=np.zeros(SHAPE, dtype=np.int32),
        config={"layers": IMCOM_MAP_CONFIG},
    )

    assert output.shape == (0,)
    assert (
        output.dtype.names
        == np.dtype(
            get_imcom_map_cat_dtype(
                imcom_map_config=IMCOM_MAP_CONFIG,
                nband=2,
            )
        ).names
    )
