"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import copy

import galsim
import ngmix
import numpy as np
import pytest

from galsim_sim import _get_obs
from metacoadd.metacal import MetacalHandler


MCAL_STEP = 0.01
FIXED_TARGET_FWHM = 1.0

IMAGE_RTOL = 1.0e-8
IMAGE_ATOL = 1.0e-10


def _get_reference_config(mcal_class, has_pixel):
    if mcal_class == "gauss_psf":
        return {
            "ngmix_psf": "fitgauss",
            "mcal_config": {
                "step": MCAL_STEP,
                "has_pixel": has_pixel,
            },
            "rng_seed": 9876,
        }

    # ngmix dilates an analytic PSF by 1 + 2 * |g|, whereas
    # MetacalFixGaussPSF interprets fwhm_target as the final FWHM.
    dilation = 1.0 + 2.0 * MCAL_STEP
    ngmix_fwhm = FIXED_TARGET_FWHM / dilation

    return {
        "ngmix_psf": galsim.Gaussian(fwhm=ngmix_fwhm),
        "mcal_config": {
            "step": MCAL_STEP,
            "has_pixel": has_pixel,
            "fwhm_target": FIXED_TARGET_FWHM,
        },
        # An RNG would make ngmix add noise to the analytic PSF.
        "rng_seed": None,
    }


def _make_matching_rngs(seed):
    if seed is None:
        return None, None

    return (
        np.random.RandomState(seed),
        np.random.RandomState(seed),
    )


@pytest.mark.parametrize(
    "mcal_class",
    ["gauss_psf", "fix_gauss_psf"],
)
@pytest.mark.parametrize("fixnoise", [False, True])
@pytest.mark.parametrize("has_pixel", [True, False])
def test_metacal_matches_ngmix_pixels(
    mcal_class,
    fixnoise,
    has_pixel,
):
    """Compare metacoadd metacal pixels with the ngmix reference."""
    obs_rng = np.random.RandomState(1234)

    obs = _get_obs(
        obs_rng,
        noise=0.005,
        set_noise_image=fixnoise,
        has_pixel=has_pixel,
    )
    assert obs.has_noise() == fixnoise

    # Both implementations receive independent copies of the same pixels.
    ngmix_obs = copy.deepcopy(obs)

    config = _get_reference_config(
        mcal_class=mcal_class,
        has_pixel=has_pixel,
    )
    metacoadd_rng, ngmix_rng = _make_matching_rngs(config["rng_seed"])

    mcal_types = list(ngmix.metacal.METACAL_MINIMAL_TYPES)

    metacoadd_handler = MetacalHandler(
        rng=metacoadd_rng,
        mcal_class=mcal_class,
        fixnoise=fixnoise,
        use_noise_image=fixnoise,
        mcal_config=config["mcal_config"],
    )
    metacoadd_res = metacoadd_handler.get_all(
        obs,
        mcal_types=mcal_types,
    )

    # ngmix has no has_pixel option. It always uses its standard pixel
    # treatment on the observation supplied to it.
    ngmix_res = ngmix.metacal.get_all_metacal(
        obs=ngmix_obs,
        psf=config["ngmix_psf"],
        step=MCAL_STEP,
        fixnoise=fixnoise,
        rng=ngmix_rng,
        use_noise_image=fixnoise,
        types=mcal_types,
    )

    assert metacoadd_res.keys() == ngmix_res.keys()

    for mcal_type in mcal_types:
        actual = metacoadd_res[mcal_type]
        expected = ngmix_res[mcal_type]

        case = (
            f"{mcal_class}/{mcal_type}, "
            f"fixnoise={fixnoise}, has_pixel={has_pixel}"
        )

        np.testing.assert_allclose(
            actual.image,
            expected.image,
            rtol=IMAGE_RTOL,
            atol=IMAGE_ATOL,
            err_msg=f"galaxy pixels differ for {case}",
        )
        np.testing.assert_allclose(
            actual.psf.image,
            expected.psf.image,
            rtol=IMAGE_RTOL,
            atol=IMAGE_ATOL,
            err_msg=f"PSF pixels differ for {case}",
        )
        np.testing.assert_allclose(
            actual.weight,
            expected.weight,
            rtol=0.0,
            atol=0.0,
            err_msg=f"weights differ for {case}",
        )
