"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import numpy as np
import pytest

import astropy.units as u
from astropy.coordinates import SkyCoord
from astropy.wcs import Sip, WCS

import galsim
import ngmix

from metacoadd.exposure import Exposure
from metacoadd.utils import (
    _exp2obs,
    _identity_njit,
    atleast_mbobs,
    shift_wcs,
)


def _make_astropy_wcs(crpix=(1024.5, 2048.5)):
    """Build a rotated celestial WCS with a small SIP distortion."""
    scale = 0.2 / 3600.0
    angle = np.deg2rad(23.0)

    wcs = WCS(naxis=2)
    wcs.wcs.crpix = np.asarray(crpix, dtype=np.float64)
    wcs.wcs.crval = [150.0, 2.0]
    wcs.wcs.ctype = [
        "RA---TAN-SIP",
        "DEC--TAN-SIP",
    ]
    wcs.wcs.cunit = ["deg", "deg"]
    wcs.wcs.cd = scale * np.array(
        [
            [-np.cos(angle), np.sin(angle)],
            [np.sin(angle), np.cos(angle)],
        ]
    )

    a = np.zeros((4, 4))
    b = np.zeros((4, 4))

    a[2, 0] = 2.0e-8
    a[1, 1] = -1.0e-8
    b[0, 2] = -1.5e-8
    b[1, 1] = 0.8e-8

    wcs.sip = Sip(
        a,
        b,
        None,
        None,
        wcs.wcs.crpix,
    )

    return wcs


@pytest.mark.coverage_all_params
@pytest.mark.parametrize(
    "use_astropy_attribute",
    [False, True],
)
def test_shift_wcs_preserves_sky_coordinates(
    use_astropy_attribute,
):
    """
    Check that a cutout pixel maps to the same sky position as its
    corresponding parent-image pixel.

    If the cutout begins at parent pixel (xmin, ymin), then cutout
    pixel (1, 1) must represent parent pixel (xmin, ymin).
    """
    astropy_wcs = _make_astropy_wcs()
    original_wcs = galsim.AstropyWCS(wcs=astropy_wcs)

    # Exercise both supported paths in shift_wcs.
    if use_astropy_attribute:
        original_wcs.astropy = astropy_wcs

    original_crpix = astropy_wcs.wcs.crpix.copy()

    offset = galsim.PositionI(
        x=1001,
        y=2001,
    )
    shifted_wcs = shift_wcs(
        original_wcs,
        offset,
    )

    expected_crpix = original_crpix - np.array(
        [
            offset.x - 1,
            offset.y - 1,
        ]
    )

    np.testing.assert_allclose(
        shifted_wcs.wcs.wcs.crpix,
        expected_crpix,
        rtol=0.0,
        atol=1.0e-12,
    )

    # shift_wcs must not modify the input WCS.
    np.testing.assert_array_equal(
        astropy_wcs.wcs.crpix,
        original_crpix,
    )

    cutout_pixels = np.array(
        [
            [1.0, 1.0],
            [24.5, 48.5],
            [73.25, 81.75],
        ]
    )
    parent_pixels = cutout_pixels + np.array(
        [
            offset.x - 1,
            offset.y - 1,
        ]
    )

    parent_world = astropy_wcs.all_pix2world(
        parent_pixels,
        1,
    )
    cutout_world = shifted_wcs.wcs.all_pix2world(
        cutout_pixels,
        1,
    )

    parent_sky = SkyCoord(
        parent_world[:, 0] * u.deg,
        parent_world[:, 1] * u.deg,
    )
    cutout_sky = SkyCoord(
        cutout_world[:, 0] * u.deg,
        cutout_world[:, 1] * u.deg,
    )

    separation = parent_sky.separation(cutout_sky)

    # This is much smaller than any relevant astrometric tolerance.
    assert np.all(separation < 1.0e-5 * u.arcsec)

    # Verify the inverse transformation independently.
    parent_pixels_recovered = astropy_wcs.all_world2pix(
        parent_world,
        1,
    )
    cutout_pixels_recovered = shifted_wcs.wcs.all_world2pix(
        parent_world,
        1,
    )

    pixel_shift = np.array(
        [
            offset.x - 1,
            offset.y - 1,
        ],
        dtype=np.float64,
    )

    expected_pixel_shifts = np.broadcast_to(
        pixel_shift,
        parent_pixels_recovered.shape,
    )

    np.testing.assert_allclose(
        parent_pixels_recovered - cutout_pixels_recovered,
        expected_pixel_shifts,
        rtol=0.0,
        atol=1.0e-7,
    )

    # Shifting the reference pixel must preserve the local scale,
    # rotation, shear, and distortion at corresponding positions.
    for cutout_pixel, parent_pixel in zip(
        cutout_pixels,
        parent_pixels,
        strict=False,
    ):
        original_jacobian = original_wcs.jacobian(
            image_pos=galsim.PositionD(
                x=parent_pixel[0],
                y=parent_pixel[1],
            )
        )
        shifted_jacobian = shifted_wcs.jacobian(
            image_pos=galsim.PositionD(
                x=cutout_pixel[0],
                y=cutout_pixel[1],
            )
        )

        original_matrix = np.array(
            [
                original_jacobian.dudx,
                original_jacobian.dudy,
                original_jacobian.dvdx,
                original_jacobian.dvdy,
            ]
        )
        shifted_matrix = np.array(
            [
                shifted_jacobian.dudx,
                shifted_jacobian.dudy,
                shifted_jacobian.dvdx,
                shifted_jacobian.dvdy,
            ]
        )

        np.testing.assert_allclose(
            shifted_matrix,
            original_matrix,
            rtol=1.0e-7,
            atol=1.0e-10,
        )


def test_shift_wcs_identity():
    """Check that offset (1, 1) leaves the pixel mapping unchanged."""
    astropy_wcs = _make_astropy_wcs()
    original_wcs = galsim.AstropyWCS(wcs=astropy_wcs)

    shifted_wcs = shift_wcs(
        original_wcs,
        galsim.PositionI(1, 1),
    )

    pixels = np.array(
        [
            [1.0, 1.0],
            [100.5, 200.5],
            [1024.5, 2048.5],
        ]
    )

    original_world = astropy_wcs.all_pix2world(
        pixels,
        1,
    )
    shifted_world = shifted_wcs.wcs.all_pix2world(
        pixels,
        1,
    )

    np.testing.assert_allclose(
        shifted_world,
        original_world,
        rtol=0.0,
        atol=1.0e-10,
    )


def test_shift_wcs_invalid_input():
    """Check rejection of a WCS without an Astropy component."""
    with pytest.raises(
        ValueError,
        match="wcs must have an astropy component",
    ):
        shift_wcs(
            galsim.PixelScale(0.2),
            galsim.PositionI(1, 1),
        )


def _make_exposure(shape, crpix, include_noise=True):
    """Build an Exposure with deterministic image layers."""
    image = np.arange(
        1,
        np.prod(shape) + 1,
        dtype=np.float64,
    ).reshape(shape)
    weight = np.full(shape, 4.0)

    noise = np.full(shape, 0.5) if include_noise else None

    return Exposure(
        image=image,
        weight=weight,
        noise=noise,
        wcs=_make_astropy_wcs(crpix=crpix),
    )


def _assert_jacobian_matches_exposure(obs, exposure):
    """Check the ngmix Jacobian against the image WCS."""
    expected_row = (exposure.image.array.shape[0] - 1) / 2
    expected_col = (exposure.image.array.shape[1] - 1) / 2

    np.testing.assert_allclose(
        obs.jacobian.get_cen(),
        (expected_row, expected_col),
    )

    # GalSim image coordinates are one-based, so true_center is the
    # appropriate position at which to evaluate the WCS Jacobian.
    expected = exposure.wcs.jacobian(
        image_pos=exposure.image.true_center,
    )

    np.testing.assert_allclose(
        [
            obs.jacobian.dudcol,
            obs.jacobian.dudrow,
            obs.jacobian.dvdcol,
            obs.jacobian.dvdrow,
        ],
        [
            expected.dudx,
            expected.dudy,
            expected.dvdx,
            expected.dvdy,
        ],
        rtol=1.0e-10,
        atol=1.0e-12,
    )


def test_exp2obs():
    """Test conversion of real galaxy and PSF exposures."""
    exposure = _make_exposure(
        shape=(9, 13),
        crpix=(7.0, 5.0),
    )
    psf_exposure = _make_exposure(
        shape=(7, 11),
        crpix=(6.0, 4.0),
        include_noise=False,
    )

    obs = _exp2obs(
        exposure,
        exp_psf=psf_exposure,
    )

    assert isinstance(obs, ngmix.Observation)
    assert obs.has_psf()

    np.testing.assert_array_equal(
        obs.image,
        exposure.image.array,
    )
    np.testing.assert_array_equal(
        obs.weight,
        exposure.weight.array,
    )
    np.testing.assert_array_equal(
        obs.noise,
        exposure.noise.array,
    )
    np.testing.assert_array_equal(
        obs.bmask,
        np.zeros_like(obs.image, dtype=np.int32),
    )
    np.testing.assert_array_equal(
        obs.ormask,
        np.zeros_like(obs.image, dtype=np.int32),
    )

    np.testing.assert_array_equal(
        obs.psf.image,
        psf_exposure.image.array,
    )
    np.testing.assert_array_equal(
        obs.psf.weight,
        psf_exposure.weight.array,
    )

    _assert_jacobian_matches_exposure(
        obs,
        exposure,
    )
    _assert_jacobian_matches_exposure(
        obs.psf,
        psf_exposure,
    )


def test_exp2obs_resampled_images():
    """Check selection of the resampled image layers."""
    exposure = _make_exposure(
        shape=(9, 9),
        crpix=(5.0, 5.0),
    )
    psf_exposure = _make_exposure(
        shape=(7, 7),
        crpix=(4.0, 4.0),
        include_noise=False,
    )

    exposure.image_resamp = galsim.Image(
        exposure.image.array * 2.0,
        wcs=exposure.wcs,
    )
    exposure.weight_resamp = galsim.Image(
        exposure.weight.array * 3.0,
        wcs=exposure.wcs,
    )
    exposure.noise_resamp = galsim.Image(
        exposure.noise.array * 4.0,
        wcs=exposure.wcs,
    )
    exposure.wcs_resamp = exposure.wcs

    psf_exposure.image_resamp = galsim.Image(
        psf_exposure.image.array * 5.0,
        wcs=psf_exposure.wcs,
    )
    psf_exposure.weight_resamp = galsim.Image(
        psf_exposure.weight.array * 6.0,
        wcs=psf_exposure.wcs,
    )
    psf_exposure.wcs_resamp = psf_exposure.wcs

    obs = _exp2obs(
        exposure,
        exp_psf=psf_exposure,
        use_resamp=True,
    )

    np.testing.assert_array_equal(
        obs.image,
        exposure.image_resamp.array,
    )
    np.testing.assert_array_equal(
        obs.weight,
        exposure.weight_resamp.array,
    )
    np.testing.assert_array_equal(
        obs.noise,
        exposure.noise_resamp.array,
    )
    np.testing.assert_array_equal(
        obs.psf.image,
        psf_exposure.image_resamp.array,
    )
    np.testing.assert_array_equal(
        obs.psf.weight,
        psf_exposure.weight_resamp.array,
    )


def test_exp2obs_without_psf():
    """Check the documented optional-PSF behavior."""
    exposure = _make_exposure(
        shape=(9, 9),
        crpix=(5.0, 5.0),
    )

    obs = _exp2obs(exposure)

    assert isinstance(obs, ngmix.Observation)
    assert not obs.has_psf()


def test_exp2obs_missing_images():
    """Test missing science and PSF image validation."""
    exposure = _make_exposure(
        shape=(9, 9),
        crpix=(5.0, 5.0),
    )

    exposure_without_image = _make_exposure(
        shape=(9, 9),
        crpix=(5.0, 5.0),
    )
    del exposure_without_image.image

    with pytest.raises(
        ValueError,
        match="Exposure has no image set",
    ):
        _exp2obs(exposure_without_image)

    psf_without_image = _make_exposure(
        shape=(7, 7),
        crpix=(4.0, 4.0),
        include_noise=False,
    )
    del psf_without_image.image

    with pytest.raises(
        ValueError,
        match="PSF Exposure has no image set",
    ):
        _exp2obs(
            exposure,
            exp_psf=psf_without_image,
        )


def test_exp2obs_without_optional_maps():
    """Test default handling of missing weight and noise maps."""
    image = np.arange(
        81,
        dtype=np.float64,
    ).reshape(9, 9)

    psf_image = np.arange(
        49,
        dtype=np.float64,
    ).reshape(7, 7)

    # Do not provide weight or noise maps.
    exposure = Exposure(
        image=image,
        wcs=_make_astropy_wcs(
            crpix=(5.0, 5.0),
        ),
    )
    psf_exposure = Exposure(
        image=psf_image,
        wcs=_make_astropy_wcs(
            crpix=(4.0, 4.0),
        ),
    )

    obs = _exp2obs(
        exposure,
        exp_psf=psf_exposure,
    )

    # ngmix replaces weight=None with a unit-weight map.
    np.testing.assert_array_equal(
        obs.weight,
        np.ones_like(image),
    )
    np.testing.assert_array_equal(
        obs.psf.weight,
        np.ones_like(psf_image),
    )

    # Unlike the weight, a missing noise map remains unset.
    assert not obs.has_noise()

    np.testing.assert_array_equal(
        obs.image,
        image,
    )
    np.testing.assert_array_equal(
        obs.psf.image,
        psf_image,
    )


def test_atleast_mbobs():
    """Test conversion of all supported observation containers."""
    obs = ngmix.Observation(
        image=np.ones((5, 5)),
    )

    from_obs = atleast_mbobs(obs)

    assert isinstance(from_obs, ngmix.MultiBandObsList)
    assert len(from_obs) == 1
    assert len(from_obs[0]) == 1
    assert from_obs[0][0] is obs

    obslist = ngmix.ObsList()
    obslist.append(obs)

    from_obslist = atleast_mbobs(obslist)

    assert isinstance(from_obslist, ngmix.MultiBandObsList)
    assert len(from_obslist) == 1
    assert from_obslist[0] is obslist

    mbobs = ngmix.MultiBandObsList()
    mbobs.append(obslist)

    from_mbobs = atleast_mbobs(mbobs)

    assert from_mbobs is mbobs

    with pytest.raises(
        ValueError,
        match="obs must be an Observation",
    ):
        atleast_mbobs(object())


def test_identity_njit():
    """Test direct and configured decorator forms."""

    def function(value):
        return value + 1

    direct = _identity_njit(function)

    assert direct is function
    assert direct(2) == 3

    configured = _identity_njit(
        cache=True,
        fastmath=True,
    )
    decorated = configured(function)

    assert decorated is function
    assert decorated(2) == 3
