"""
The tests were generated by ChatGPT 5.6 Sol.
"""

from types import SimpleNamespace
from unittest.mock import Mock

import numpy as np

from metacoadd import masking
from metacoadd.masking import (
    get_mask_and_bmask,
    get_radius_arcsec,
)


def _make_star_cat(ra, dec, mag):
    """Build a minimal star catalog matching the current interface."""
    return {
        "ra": SimpleNamespace(
            values=np.asarray(ra, dtype=np.float64),
        ),
        "dec": SimpleNamespace(
            values=np.asarray(dec, dtype=np.float64),
        ),
        "mag_AB": SimpleNamespace(
            values=np.asarray(mag, dtype=np.float64),
        ),
    }


def _make_wcs(
    x,
    y,
    pixel_scale=1.0,
    array_shape=(11, 11),
):
    """Build a mock WCS with deterministic pixel coordinates."""
    wcs = Mock()
    scale_degrees = pixel_scale / 3600.0

    wcs.pixel_scale_matrix = np.asarray(
        [
            [scale_degrees, 0.0],
            [0.0, scale_degrees],
        ]
    )
    wcs.array_shape = array_shape
    wcs.all_world2pix.return_value = (
        np.asarray(x, dtype=np.float64),
        np.asarray(y, dtype=np.float64),
    )

    return wcs


def test_get_radius_arcsec():
    """Test scalar and array polynomial radius calculations."""
    coeffs = [0.1, -1.0]

    magnitudes = np.asarray([10.0, 15.0, 20.0])
    expected = np.asarray(
        [
            1.0,
            np.sqrt(10.0),
            10.0,
        ]
    )

    radius = get_radius_arcsec(
        mag=magnitudes,
        coeffs=coeffs,
    )

    np.testing.assert_allclose(radius, expected)

    scalar_radius = get_radius_arcsec(
        mag=15.0,
        coeffs=coeffs,
    )
    np.testing.assert_allclose(
        scalar_radius,
        np.sqrt(10.0),
    )


def test_get_mask_and_bmask_arguments(monkeypatch):
    """Test star selection, radius clipping, and mask arguments."""
    star_cat = _make_star_cat(
        ra=[10.0, 11.0, 12.0, 13.0],
        dec=[-1.0, -2.0, -3.0, -4.0],
        mag=[20.0, 25.0, 24.0, 26.0],
    )
    wcs = _make_wcs(
        x=[1.0, 2.0, 3.0, 4.0],
        y=[4.0, 5.0, 6.0, 7.0],
        pixel_scale=-1.0,
        array_shape=(8, 10),
    )

    expected_mask = np.full((8, 10), 0.5)
    expected_bmask = np.full(
        (8, 10),
        8,
        dtype=np.int32,
    )

    make_apodization_mask = Mock(
        return_value=expected_mask,
    )
    make_bmask = Mock(
        return_value=expected_bmask,
    )

    monkeypatch.setattr(
        masking,
        "make_foreground_apodization_mask",
        make_apodization_mask,
    )
    monkeypatch.setattr(
        masking,
        "make_foreground_bmask",
        make_bmask,
    )

    mask, bmask = get_mask_and_bmask(
        wcs=wcs,
        star_cat=star_cat,
        poly_coeffs=[np.log10(2.0)],
    )

    assert mask is expected_mask
    assert bmask is expected_bmask

    wcs.all_world2pix.assert_called_once()
    ra, dec, origin = wcs.all_world2pix.call_args.args

    np.testing.assert_array_equal(
        ra,
        star_cat["ra"].values,
    )
    np.testing.assert_array_equal(
        dec,
        star_cat["dec"].values,
    )
    assert origin == 0

    apodization_kwargs = make_apodization_mask.call_args.kwargs

    # Magnitudes 20 and 24 pass the strict mag < 25 cut.
    np.testing.assert_array_equal(
        apodization_kwargs["xm"],
        [1.0, 3.0],
    )
    np.testing.assert_array_equal(
        apodization_kwargs["ym"],
        [4.0, 6.0],
    )

    # The polynomial gives 2 arcsec. With a 1 arcsec/pixel
    # scale, this becomes 2 pixels and is clipped to 3 pixels.
    np.testing.assert_array_equal(
        apodization_kwargs["rm"],
        [3.0, 3.0],
    )
    assert apodization_kwargs["dims"] == (8, 10)
    assert apodization_kwargs["symmetrize"] is False
    assert apodization_kwargs["ap_rad"] == 7

    bmask_kwargs = make_bmask.call_args.kwargs

    np.testing.assert_array_equal(
        bmask_kwargs["xm"],
        [1.0, 3.0],
    )
    np.testing.assert_array_equal(
        bmask_kwargs["ym"],
        [4.0, 6.0],
    )

    # The default bmask expansion adds 20 pixels.
    np.testing.assert_array_equal(
        bmask_kwargs["rm"],
        [23.0, 23.0],
    )
    assert bmask_kwargs["dims"] == (8, 10)
    assert bmask_kwargs["symmetrize"] is False
    assert bmask_kwargs["mask_bit_val"] == 8


def test_get_mask_and_bmask_custom_arguments(monkeypatch):
    """Test forwarding of custom masking parameters."""
    star_cat = _make_star_cat(
        ra=[10.0],
        dec=[-2.0],
        mag=[20.0],
    )
    wcs = _make_wcs(
        x=[5.0],
        y=[6.0],
        pixel_scale=2.0,
        array_shape=(12, 14),
    )

    make_apodization_mask = Mock(
        return_value=np.ones((12, 14)),
    )
    make_bmask = Mock(
        return_value=np.zeros(
            (12, 14),
            dtype=np.int32,
        ),
    )

    monkeypatch.setattr(
        masking,
        "make_foreground_apodization_mask",
        make_apodization_mask,
    )
    monkeypatch.setattr(
        masking,
        "make_foreground_bmask",
        make_bmask,
    )

    get_mask_and_bmask(
        wcs=wcs,
        star_cat=star_cat,
        poly_coeffs=[np.log10(4.0)],
        mag_max=21.0,
        min_radius=1.0,
        ap_radius=2.5,
        bmask_expand=4.0,
        bmask_bit_val=32,
    )

    apodization_kwargs = make_apodization_mask.call_args.kwargs

    # Four arcsec with a 2 arcsec/pixel scale gives 2 pixels.
    np.testing.assert_allclose(
        apodization_kwargs["rm"],
        [2.0],
    )
    assert apodization_kwargs["ap_rad"] == 2.5
    assert apodization_kwargs["dims"] == (12, 14)

    bmask_kwargs = make_bmask.call_args.kwargs

    np.testing.assert_allclose(
        bmask_kwargs["rm"],
        [6.0],
    )
    assert bmask_kwargs["mask_bit_val"] == 32
    assert bmask_kwargs["dims"] == (12, 14)


def test_get_mask_and_bmask_no_selected_stars(monkeypatch):
    """Test mask construction when every star fails the magnitude cut."""
    star_cat = _make_star_cat(
        ra=[10.0, 11.0],
        dec=[-1.0, -2.0],
        mag=[26.0, 27.0],
    )
    wcs = _make_wcs(
        x=[4.0, 6.0],
        y=[5.0, 7.0],
    )

    expected_mask = np.ones((11, 11))
    expected_bmask = np.zeros(
        (11, 11),
        dtype=np.int32,
    )

    make_apodization_mask = Mock(
        return_value=expected_mask,
    )
    make_bmask = Mock(
        return_value=expected_bmask,
    )

    monkeypatch.setattr(
        masking,
        "make_foreground_apodization_mask",
        make_apodization_mask,
    )
    monkeypatch.setattr(
        masking,
        "make_foreground_bmask",
        make_bmask,
    )

    mask, bmask = get_mask_and_bmask(
        wcs=wcs,
        star_cat=star_cat,
        poly_coeffs=[0.0],
        mag_max=25.0,
    )

    assert mask is expected_mask
    assert bmask is expected_bmask

    apodization_kwargs = make_apodization_mask.call_args.kwargs
    bmask_kwargs = make_bmask.call_args.kwargs

    assert apodization_kwargs["xm"].size == 0
    assert apodization_kwargs["ym"].size == 0
    assert apodization_kwargs["rm"].size == 0

    assert bmask_kwargs["xm"].size == 0
    assert bmask_kwargs["ym"].size == 0
    assert bmask_kwargs["rm"].size == 0


def test_get_mask_and_bmask_integration():
    """Test construction of real metadetect masks."""
    star_cat = _make_star_cat(
        ra=[10.0],
        dec=[-2.0],
        mag=[20.0],
    )
    wcs = _make_wcs(
        x=[5.0],
        y=[5.0],
        pixel_scale=1.0,
        array_shape=(11, 11),
    )
    bit_value = 32

    mask, bmask = get_mask_and_bmask(
        wcs=wcs,
        star_cat=star_cat,
        poly_coeffs=[np.log10(2.0)],
        min_radius=0.0,
        ap_radius=0.1,
        bmask_expand=1.0,
        bmask_bit_val=bit_value,
    )

    assert mask.shape == (11, 11)
    assert bmask.shape == (11, 11)
    assert bmask.dtype == np.int32

    assert np.all(mask >= 0.0)
    assert np.all(mask <= 1.0)

    # The star is centered at pixel (5, 5).
    assert mask[5, 5] < 1.0
    assert (bmask[5, 5] & bit_value) != 0

    # A distant corner must remain unaffected.
    assert mask[0, 0] == 1.0
    assert (bmask[0, 0] & bit_value) == 0
