"""
The tests were generated by ChatGPT 5.6 Sol.
"""

import pytest
import os

if os.environ.get("COVERAGE_MODE", "0") == "1":
    os.environ["TESTING_DETECT"] = "1"

import numpy as np

from astropy.wcs import WCS

import galsim
import ngmix

from metacoadd.detect import (
    DET_CAT_DTYPE,
    get_cat,
    get_cutout,
    get_cutout_size,
    get_filter_kernel,
    get_output_cat,
    get_pixel_scale,
    get_stamp_mbobs,
    get_xyToradec_func,
    reduce_mask_by_segmentation,
)


def _make_astropy_wcs(
    scale=0.2,
    angle=27.0,
):
    """Build a rotated TAN WCS."""
    angle = np.deg2rad(angle)
    scale_deg = scale / 3600.0

    wcs = WCS(naxis=2)
    wcs.wcs.crpix = [51.0, 51.0]
    wcs.wcs.crval = [150.0, 2.0]
    wcs.wcs.ctype = ["RA---TAN", "DEC--TAN"]
    wcs.wcs.cunit = ["deg", "deg"]
    wcs.wcs.cd = scale_deg * np.array(
        [
            [-np.cos(angle), np.sin(angle)],
            [np.sin(angle), np.cos(angle)],
        ]
    )

    return wcs


def _make_detection_row(
    x=5.0,
    y=5.0,
    number=1,
):
    """Build the fields required by get_stamp_mbobs."""
    dtype = [
        ("number", np.int64),
        ("x", np.float64),
        ("y", np.float64),
        ("xx", np.float64),
        ("xy", np.float64),
        ("yy", np.float64),
    ]

    return np.array(
        [
            (
                number,
                x,
                y,
                0.16,
                0.0,
                0.16,
            )
        ],
        dtype=dtype,
    )[0]


def _make_mbobs(nband=2):
    """Build deterministic multiband observations."""
    shape = (11, 11)
    mbobs = ngmix.MultiBandObsList()

    for band_index in range(nband):
        image = (
            np.arange(
                np.prod(shape),
                dtype=np.float64,
            ).reshape(shape)
            + 1000 * band_index
        )
        weight = np.full(
            shape,
            10.0 * (band_index + 1),
        )
        noise = np.full(
            shape,
            -(band_index + 1.0),
        )

        bmask = np.zeros(shape, dtype=np.int32)
        bmask[5, 5] = 1 << band_index
        bmask[4, 6] = 4 << band_index

        ormask = np.zeros(shape, dtype=np.int32)
        ormask[5, 5] = 16 << band_index
        ormask[4, 6] = 64 << band_index

        jacobian = ngmix.Jacobian(
            row=5.0,
            col=5.0,
            dudrow=0.01,
            dudcol=0.20,
            dvdrow=0.19,
            dvdcol=-0.02,
        )

        psf_jacobian = ngmix.DiagonalJacobian(
            row=2.0,
            col=2.0,
            scale=0.2,
        )
        psf = ngmix.Observation(
            image=np.ones((5, 5)),
            weight=np.ones((5, 5)),
            jacobian=psf_jacobian,
        )

        obs = ngmix.Observation(
            image=image,
            weight=weight,
            noise=noise,
            bmask=bmask,
            ormask=ormask,
            jacobian=jacobian,
            psf=psf,
        )
        obs.ps = np.full(shape, band_index + 0.5)

        obslist = ngmix.ObsList()
        obslist.append(obs)
        mbobs.append(obslist)

    return mbobs


def test_get_cutout_size():
    """Check the covariance-eigenvalue definition of the stamp size."""
    cases = [
        np.array(
            [
                [4.0, 0.0],
                [0.0, 4.0],
            ]
        ),
        np.array(
            [
                [9.0, 0.0],
                [0.0, 1.0],
            ]
        ),
    ]

    angle = np.deg2rad(37.0)
    rotation = np.array(
        [
            [np.cos(angle), -np.sin(angle)],
            [np.sin(angle), np.cos(angle)],
        ]
    )
    cases.append(rotation @ np.diag([9.0, 1.0]) @ rotation.T)

    n_sigma = 3.0

    for covariance in cases:
        expected = 2.0 * n_sigma * np.sqrt(np.linalg.eigvalsh(covariance).max())

        measured = get_cutout_size(
            Qxx=covariance[0, 0],
            Qxy=covariance[0, 1],
            Qyy=covariance[1, 1],
            n_sigma=n_sigma,
        )

        np.testing.assert_allclose(
            measured,
            expected,
            rtol=1.0e-12,
            atol=0.0,
        )


def test_detection_position_is_preserved_in_stamp():
    """
    Detect a source and extract its stamp using the same sequence as
    MetaDetect.

    The detected source must remain at the Jacobian reference position
    in the extracted observation.
    """
    image_size = 64
    source_x = 31.37
    source_y = 28.61
    sigma = 1.5
    flux_scale = 100.0

    rows, cols = np.mgrid[
        :image_size,
        :image_size,
    ]
    image = flux_scale * np.exp(
        -0.5
        * (((cols - source_x) / sigma) ** 2 + ((rows - source_y) / sigma) ** 2)
    )

    weight = np.ones_like(image)
    noise = np.zeros_like(image)
    bmask = np.zeros_like(image, dtype=np.int32)
    ormask = np.zeros_like(image, dtype=np.int32)

    jacobian = ngmix.Jacobian(
        row=(image_size - 1) / 2,
        col=(image_size - 1) / 2,
        dudrow=0.0,
        dudcol=0.2,
        dvdrow=0.2,
        dvdcol=0.0,
    )

    obs = ngmix.Observation(
        image=image,
        weight=weight,
        noise=noise,
        bmask=bmask,
        ormask=ormask,
        jacobian=jacobian,
    )

    obslist = ngmix.ObsList()
    obslist.append(obs)

    mbobs = ngmix.MultiBandObsList()
    mbobs.append(obslist)

    detection_kernel = [
        [0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0],
    ]

    catalog, segmentation = get_cat(
        img=image,
        weight=weight,
        thresh_type="absolute",
        thresh=1.0,
        minarea=5,
        kernel=detection_kernel,
        filter_type="conv",
    )

    assert len(catalog) == 1

    detection = catalog[0]

    np.testing.assert_allclose(
        detection["x"],
        source_x,
        atol=0.03,
    )
    np.testing.assert_allclose(
        detection["y"],
        source_y,
        atol=0.03,
    )

    stamp_size = 15

    stamp_mbobs = get_stamp_mbobs(
        mbobs,
        detection,
        min_stamp_size=stamp_size,
        max_stamp_size=stamp_size,
        do_uberseg=True,
        seg_map=segmentation,
    )

    stamp = stamp_mbobs[0][0]

    # Independently reproduce the currently intended cutout convention.
    half_size = stamp_size // 2
    row_start = int(detection["y"]) - half_size + 1
    col_start = int(detection["x"]) - half_size + 1

    np.testing.assert_array_equal(
        stamp.image,
        image[
            row_start : row_start + stamp_size,
            col_start : col_start + stamp_size,
        ],
    )

    expected_stamp_row = detection["y"] - row_start
    expected_stamp_col = detection["x"] - col_start

    np.testing.assert_allclose(
        stamp.jacobian.row0,
        expected_stamp_row,
        atol=1.0e-12,
    )
    np.testing.assert_allclose(
        stamp.jacobian.col0,
        expected_stamp_col,
        atol=1.0e-12,
    )

    # Detect the source again inside the stamp. Its measured position
    # must coincide with the Jacobian reference position assigned by
    # get_stamp_mbobs.
    stamp_catalog, _ = get_cat(
        img=stamp.image.copy(),
        weight=stamp.weight,
        thresh_type="absolute",
        thresh=1.0,
        minarea=5,
        kernel=detection_kernel,
        filter_type="conv",
    )

    assert len(stamp_catalog) == 1

    np.testing.assert_allclose(
        stamp_catalog["x"][0],
        stamp.jacobian.col0,
        atol=1.0e-6,
    )
    np.testing.assert_allclose(
        stamp_catalog["y"][0],
        stamp.jacobian.row0,
        atol=1.0e-6,
    )


def test_get_cutout_zero_padding():
    """Check edge padding using the established +1 convention."""
    image = np.arange(
        1,
        26,
    ).reshape(5, 5)

    cutout, row, col = get_cutout(
        image,
        x=0.0,
        y=0.0,
        stamp_size=5,
    )

    expected = np.zeros(
        (5, 5),
        dtype=image.dtype,
    )
    expected[1:5, 1:5] = image[0:4, 0:4]

    np.testing.assert_array_equal(
        cutout,
        expected,
    )
    assert row == 1.0
    assert col == 1.0

    # The requested source position maps to the returned local position.
    assert cutout[int(row), int(col)] == image[0, 0]


def test_get_stamp_mbobs():
    """Check cutout data, masks, centers, and WCS derivatives."""
    mbobs = _make_mbobs()
    detection = _make_detection_row()

    segmentation = np.ones(
        mbobs[0][0].image.shape,
        dtype=np.int32,
    )

    stamps = get_stamp_mbobs(
        mbobs,
        detection,
        min_stamp_size=5,
        max_stamp_size=5,
        do_uberseg=True,
        seg_map=segmentation,
    )

    assert isinstance(stamps, ngmix.MultiBandObsList)
    assert len(stamps) == len(mbobs)

    for band_index, obslist in enumerate(stamps):
        assert len(obslist) == 1

        original = mbobs[band_index][0]
        stamp = obslist[0]

        np.testing.assert_array_equal(
            stamp.image,
            original.image[4:9, 4:9],
        )
        np.testing.assert_array_equal(
            stamp.weight,
            original.weight[4:9, 4:9],
        )
        np.testing.assert_array_equal(
            stamp.noise,
            original.noise[4:9, 4:9],
        )
        np.testing.assert_array_equal(
            stamp.bmask,
            original.bmask[4:9, 4:9],
        )
        np.testing.assert_array_equal(
            stamp.ormask,
            original.ormask[4:9, 4:9],
        )

        assert stamp.jacobian.row0 == detection["y"] - 4
        assert stamp.jacobian.col0 == detection["x"] - 4

        assert stamp.jacobian.get_dudrow() == (original.jacobian.get_dudrow())
        assert stamp.jacobian.get_dudcol() == (original.jacobian.get_dudcol())
        assert stamp.jacobian.get_dvdrow() == (original.jacobian.get_dvdrow())
        assert stamp.jacobian.get_dvdcol() == (original.jacobian.get_dvdcol())


def test_get_stamp_mbobs_validation_and_zero_weight():
    """Check uberseg validation and the empty-cutout safeguard."""
    mbobs = _make_mbobs(nband=1)
    detection = _make_detection_row()

    with pytest.raises(
        ValueError,
        match="seg_map must be provided",
    ):
        get_stamp_mbobs(
            mbobs,
            detection,
            min_stamp_size=5,
            max_stamp_size=5,
            do_uberseg=True,
        )

    # ngmix requires at least one positive parent-image weight. Place it
    # outside the object cutout so that the extracted weight is all zero.
    parent_weight = np.zeros_like(mbobs[0][0].weight)
    parent_weight[0, 0] = 1.0
    mbobs[0][0].set_weight(parent_weight)

    stamps = get_stamp_mbobs(
        mbobs,
        detection,
        min_stamp_size=5,
        max_stamp_size=5,
    )

    expected_weight = np.zeros((5, 5))
    expected_weight[0, 0] = 1.0

    np.testing.assert_array_equal(
        stamps[0][0].weight,
        expected_weight,
    )

    mbobs_without_noise = _make_mbobs(
        nband=1,
    )
    mbobs_without_noise[0][0].set_noise(None)

    assert not mbobs_without_noise[0][0].has_noise()

    stamps_without_noise = get_stamp_mbobs(
        mbobs_without_noise,
        detection,
        min_stamp_size=5,
        max_stamp_size=5,
    )

    assert not stamps_without_noise[0][0].has_noise()


def test_get_output_cat():
    """Check catalog initialization and field dtypes."""
    output = get_output_cat(3)

    assert output.shape == (3,)
    assert output.dtype == np.dtype(DET_CAT_DTYPE)

    for name in output.dtype.names:
        np.testing.assert_array_equal(
            output[name],
            np.zeros(3),
        )


def test_get_pixel_scale():
    """Check scalar pixel scale independently of WCS rotation."""
    astropy_wcs = _make_astropy_wcs(
        scale=0.2,
        angle=31.0,
    )

    np.testing.assert_allclose(
        get_pixel_scale(astropy_wcs),
        0.2,
        rtol=1.0e-12,
    )
    np.testing.assert_allclose(
        get_pixel_scale(galsim.PixelScale(0.3)),
        0.3,
        rtol=1.0e-12,
    )
    assert get_pixel_scale(None) == 1.0

    with pytest.raises(
        ValueError,
        match="wcs must be an astropy",
    ):
        get_pixel_scale(object())


def test_get_filter_kernel():
    """Check explicit and physically configured detection kernels."""
    explicit = [
        [0.0, -1.0, 0.0],
        [-1.0, 4.0, -1.0],
        [0.0, -1.0, 0.0],
    ]

    np.testing.assert_array_equal(
        get_filter_kernel(explicit),
        np.asarray(explicit),
    )

    pixel_scale = 0.2
    fwhm = 0.7

    kernel = get_filter_kernel(
        {
            "type": "Gaussian",
            "fwhm": fwhm,
        },
        wcs=galsim.PixelScale(pixel_scale),
    )

    assert kernel.ndim == 2
    assert np.all(np.isfinite(kernel))
    assert kernel.sum() > 0

    # GalSim drawing may produce tiny negative values from numerical
    # ringing. Require their total magnitude to be negligible rather
    # than requiring every pixel to be non-negative.
    negative_flux = np.abs(kernel[kernel < 0]).sum()
    positive_flux = kernel[kernel > 0].sum()

    assert negative_flux < 1.0e-6 * positive_flux

    rows, cols = np.indices(kernel.shape)
    normalization = kernel.sum()

    center_row = np.sum(rows * kernel) / normalization
    center_col = np.sum(cols * kernel) / normalization

    expected_row = (kernel.shape[0] - 1) / 2
    expected_col = (kernel.shape[1] - 1) / 2

    np.testing.assert_allclose(
        center_row,
        expected_row,
        atol=1.0e-5,
    )
    np.testing.assert_allclose(
        center_col,
        expected_col,
        atol=1.0e-5,
    )

    sigma_pixels = fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0)) * pixel_scale)

    measured_variance = np.sum(
        ((rows - center_row) ** 2 + (cols - center_col) ** 2) * kernel
    ) / (2.0 * normalization)

    np.testing.assert_allclose(
        np.sqrt(measured_variance),
        sigma_pixels,
        rtol=0.03,
    )

    # GalSim's special None profile builds successfully but returns
    # no GSObject.
    with pytest.raises(
        ValueError,
        match="Failed to build kernel",
    ):
        get_filter_kernel(
            {"type": "None"},
            wcs=galsim.PixelScale(0.2),
        )

    with pytest.raises(
        ValueError,
        match="kernel must be a list or a dict",
    ):
        get_filter_kernel(
            "invalid kernel",
        )


def test_get_xyToradec_func():
    """Check Astropy, celestial GalSim, and Euclidean GalSim WCSs."""
    astropy_wcs = _make_astropy_wcs()
    x = np.array([20.0, 50.0, 80.0])
    y = np.array([30.0, 50.0, 70.0])

    astropy_converter = get_xyToradec_func(astropy_wcs)
    measured = np.column_stack(astropy_converter(x, y))
    expected = np.column_stack(
        astropy_wcs.all_pix2world(
            x,
            y,
            0,
        )
    )

    np.testing.assert_allclose(
        measured,
        expected,
        rtol=0.0,
        atol=1.0e-12,
    )

    galsim_wcs = galsim.AstropyWCS(wcs=astropy_wcs)
    galsim_converter = get_xyToradec_func(galsim_wcs)

    measured = np.column_stack(galsim_converter(x, y))
    expected = np.column_stack(
        astropy_wcs.all_pix2world(
            x,
            y,
            1,
        )
    )

    np.testing.assert_allclose(
        measured,
        expected,
        rtol=0.0,
        atol=1.0e-10,
    )

    affine = galsim.AffineTransform(
        dudx=0.20,
        dudy=0.03,
        dvdx=-0.02,
        dvdy=0.19,
        origin=galsim.PositionD(4.0, 5.0),
        world_origin=galsim.PositionD(1.0, -2.0),
    )
    affine_converter = get_xyToradec_func(affine)

    u, v = affine_converter(7.0, 9.0)

    np.testing.assert_allclose(
        [u, v],
        [
            1.0 + 0.20 * 3.0 + 0.03 * 4.0,
            -2.0 - 0.02 * 3.0 + 0.19 * 4.0,
        ],
    )

    with pytest.raises(
        ValueError,
        match="wcs must be an astropy",
    ):
        get_xyToradec_func(object())


def test_reduce_mask_by_segmentation():
    """Check bitwise mask propagation over complete object footprints."""
    segmentation = np.array(
        [
            [0, 1, 1, 0],
            [2, 1, 0, 3],
            [2, 2, 4, 0],
        ]
    )

    mask = np.array(
        [
            [256, 1, 4, 0],
            [2, 8, 0, 64],
            [16, 32, 128, 0],
        ],
        dtype=np.int64,
    )

    values = reduce_mask_by_segmentation(
        mask,
        segmentation,
        n_obj=3,
    )

    np.testing.assert_array_equal(
        values,
        [
            1 | 4 | 8,
            2 | 16 | 32,
            64,
        ],
    )

    # Background pixels and labels above n_obj must be ignored.
    assert not np.any(values & 128)
    assert not np.any(values & 256)

    np.testing.assert_array_equal(
        reduce_mask_by_segmentation(
            None,
            segmentation,
            n_obj=3,
        ),
        np.zeros(3, dtype=np.int64),
    )

    with pytest.raises(
        ValueError,
        match="must have the same shape",
    ):
        reduce_mask_by_segmentation(
            np.zeros((2, 2)),
            segmentation,
            n_obj=3,
        )


def _make_gaussian_detection_image():
    """Build a noiseless elliptical Gaussian with known properties."""
    shape = (81, 81)
    rows, cols = np.indices(shape)

    x0 = 40.3
    y0 = 38.7
    sigma_x = 3.0
    sigma_y = 2.0
    flux = 10000.0

    profile = np.exp(
        -0.5 * (((cols - x0) / sigma_x) ** 2 + ((rows - y0) / sigma_y) ** 2)
    )
    image = flux * profile / np.sum(profile)

    noise = 1.0
    weight = np.full(
        shape,
        1.0 / noise**2,
    )

    bmask = np.zeros(shape, dtype=np.int32)
    ormask = np.zeros(shape, dtype=np.int32)

    center_row = int(round(y0))
    center_col = int(round(x0))

    bmask[center_row, center_col] = 1
    bmask[center_row, center_col + 1] = 4
    bmask[0, 0] = 16

    ormask[center_row, center_col] = 2
    ormask[center_row + 1, center_col] = 8
    ormask[0, 0] = 32

    return {
        "image": image,
        "weight": weight,
        "bmask": bmask,
        "ormask": ormask,
        "x0": x0,
        "y0": y0,
        "flux": flux,
    }


@pytest.mark.coverage_all_params
@pytest.mark.parametrize(
    "thresh_type",
    ["relative", "absolute"],
)
def test_get_cat_gaussian_source(thresh_type):
    """Check detection and measurement of a known Gaussian source."""
    data = _make_gaussian_detection_image()

    catalog, segmentation = get_cat(
        img=data["image"],
        weight=data["weight"],
        thresh_type=thresh_type,
        thresh=3.0,
        minarea=5,
        kernel=[[1.0]],
        bmask=data["bmask"],
        ormask=data["ormask"],
    )

    assert len(catalog) == 1
    obj = catalog[0]

    np.testing.assert_allclose(
        [obj["x"], obj["y"]],
        [data["x0"], data["y0"]],
        atol=0.1,
        rtol=0.0,
    )

    assert obj["number"] == 1
    assert obj["npix"] == np.count_nonzero(segmentation == 1)
    assert obj["flags"] == 0
    assert obj["flux_flags"] == 0

    assert obj["a"] > obj["b"] > 0
    assert obj["xx"] > obj["yy"] > 0
    assert abs(obj["xy"]) < 0.2
    assert obj["kronrad"] > 0
    assert obj["flux_radius"] > 0
    assert obj["flux_err"] > 0
    assert obj["snr"] > 0

    np.testing.assert_allclose(
        obj["elongation"],
        obj["a"] / obj["b"],
    )
    np.testing.assert_allclose(
        obj["ellipticity"],
        1.0 - obj["b"] / obj["a"],
    )
    np.testing.assert_allclose(
        obj["snr"],
        obj["flux"] / obj["flux_err"],
    )

    # A 2.5-Kron aperture should recover nearly all the Gaussian flux.
    np.testing.assert_allclose(
        obj["flux"],
        data["flux"],
        rtol=0.03,
    )

    center_row = int(round(data["y0"]))
    center_col = int(round(data["x0"]))

    assert segmentation[center_row, center_col] == 1

    # Only mask bits inside the segmentation footprint propagate.
    assert obj["bmask"] == (1 | 4)
    assert obj["ormask"] == (2 | 8)


def test_get_cat_validation():
    """Check conflicting WCS and invalid configuration errors."""
    data = _make_gaussian_detection_image()
    wcs = _make_astropy_wcs()

    with pytest.raises(
        ValueError,
        match="Only one of header or wcs",
    ):
        get_cat(
            img=data["image"],
            weight=data["weight"],
            header=wcs.to_header(),
            wcs=wcs,
            kernel=[[1.0]],
        )

    with pytest.raises(
        ValueError,
        match="Unknown thresh_type",
    ):
        get_cat(
            img=data["image"],
            weight=data["weight"],
            thresh_type="invalid",
            kernel=[[1.0]],
        )

    catalog, segmentation = get_cat(
        img=data["image"],
        weight=data["weight"],
        thresh_type="absolute",
        thresh=3.0,
        minarea=5,
        kernel=[[1.0]],
        header=wcs.to_header(),
    )

    assert len(catalog) == 1
    assert segmentation.shape == data["image"].shape

    np.testing.assert_allclose(
        [
            catalog["x"][0],
            catalog["y"][0],
        ],
        [
            data["x0"],
            data["y0"],
        ],
        rtol=0.0,
        atol=0.1,
    )
