
# This workflow will install Python dependencies, build the package and then build the documentation.

name: Build documentation


on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: metacoadd
        environment-file: environment.yml
        cache-environment: true
        generate-run-shell: true

    - name: Install package and docs dependencies
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[docs]"

    - name: Build docs
      shell: micromamba-shell {0}
      run: |
        sphinx-build -T -E -b html \
          -d docs/build/doctrees \
          docs \
          docs/build/html
