# This workflow will run daily at 06:45.
# It will install Python dependencies and run tests with a variety of Python versions.
# See documentation for help debugging smoke test issues:
#    https://lincc-ppt.readthedocs.io/en/latest/practices/ci_testing.html#version-culprit

name: Unit test smoke test

on:

  # Runs this workflow automatically
  schedule:
    - cron: 45 6 * * *
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v7

    - uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: metacoadd
        environment-file: environment.yml
        cache-environment: true
        generate-run-shell: true
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install package
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[dev]"

    - name: List dependencies
      shell: micromamba-shell {0}
      run: |
        pip list

    - name: Run unit tests with pytest
      shell: micromamba-shell {0}
      run: |
        python -m pytest