
# This workflow will install Python dependencies, run tests and report code coverage with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: shear-tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: mamba-org/setup-micromamba@v3
      with:
        environment-name: metacoadd
        environment-file: environment.yml
        # cache-environment: true
        generate-run-shell: true
        create-args: >-
          python=3.14

    - name: Install package
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[dev]"

    - name: Run tests with Numba JIT enabled
      shell: micromamba-shell {0}
      run: |
        pytest tests/shear_meas -vvv
